/*******************************************************************************
 * Copyright (c) 2006-2011
 * Software Technology Group, Dresden University of Technology
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0 
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *   Software Technology Group - TU Dresden, Germany 
 *      - initial API and implementation
 ******************************************************************************/
package org.emftext.sdk.concretesyntax.resource.cs.grammar;

/**
 * This class provides the follow sets for all terminals of the grammar. These
 * sets are used during code completion.
 */
public class CsFollowSetProvider {
	
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_0 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_24_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_1 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedBooleanTerminal(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_2 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_2);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_3 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_4);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_4 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_6);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_5 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_8);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_6 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_9_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_7 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_11_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_8 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_12_0_0_2);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_9 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_13_0_0_2);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_10 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_14_0_0_2);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_11 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_15_0_0_2);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_12 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_18);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_13 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_11_0_0_2_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_14 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_11_0_0_3_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_15 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_11_0_0_3_0_0_1_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_16 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_12_0_0_4);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_17 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_1_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_18 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_12_0_0_7);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_19 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_13_0_0_4);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_20 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_2_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_21 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_13_0_0_7);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_22 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_13_0_0_5_0_0_2);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_23 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_14_0_0_4);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_24 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_17_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_25 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_18_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_26 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_19_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_27 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_20_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_28 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_14_0_0_7);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_29 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_14_0_0_5_0_0_2);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_30 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_15_0_0_4);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_31 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_23_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_32 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_15_0_0_7);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_33 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_20);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_34 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_3_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_35 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_0_0_0_23);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_36 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_1_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_37 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_1_0_0_2);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_38 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_1_0_0_3_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_39 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_1_0_0_4_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_40 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_1_0_0_4_0_0_3);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_41 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_1_0_0_4_0_0_5);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_42 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_1_0_0_4_0_0_6_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_43 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_2_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_44 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_2_0_0_2);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_45 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_3_0_0_3);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_46 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_6_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_47 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_7_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_48 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_8_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_49 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_9_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_50 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_10_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_51 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_11_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_52 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_13_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_53 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_14_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_54 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_15_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_55 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_16_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_56 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_3_0_0_6);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_57 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_5_0_0_1_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_58 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_14_0_0_2);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_59 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_7_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_60 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_7_0_0_2);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_61 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_7_0_0_3);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_62 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedEnumerationTerminal(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_7_0_0_4);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_63 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_8_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_64 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_8_0_0_2);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_65 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedEnumerationTerminal(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_8_0_0_3);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_66 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_9_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_67 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_9_0_0_2);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_68 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_9_0_0_3);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_69 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_9_0_0_4);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_70 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_9_0_0_5_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_71 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_9_0_0_6);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_72 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_9_0_0_5_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_73 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedEnumerationTerminal(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_9_0_0_7);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_74 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_10_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_75 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_10_0_0_2);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_76 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_10_0_0_4);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_77 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_10_0_0_6);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_78 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_10_0_0_7);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_79 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedEnumerationTerminal(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_10_0_0_8);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_80 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_11_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_81 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_12_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_82 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_11_0_0_3_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_83 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_11_0_0_4);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_84 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedEnumerationTerminal(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_11_0_0_5);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_85 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_12_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_86 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_12_0_0_2);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_87 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_13_0_0_1_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_88 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedEnumerationTerminal(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_13_0_0_2);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_89 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_13_0_0_1_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_90 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_13_0_0_1_0_0_2_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_91 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_13_0_0_1_0_0_2_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_92 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedEnumerationTerminal(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_14_0_0_3);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_93 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_17_0_0_3);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_94 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_17_0_0_4);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_95 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_17_0_0_5);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_96 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_21_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_97 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_22_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_98 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_17_0_0_8_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_99 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_18_0_0_3);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_100 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_18_0_0_6_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_101 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_18_0_0_7_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_102 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_18_0_0_7_0_0_3);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_103 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_18_0_0_7_0_0_5);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_104 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_19_0_0_2);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_105 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_19_0_0_4);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_106 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_19_0_0_7_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_107 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_20_0_0_2);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_108 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_23_0_0_1_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_109 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_23_0_0_3);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_110 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_23_0_0_1_0_0_2);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_111 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_23_0_0_5);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_112 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_23_0_0_6_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_113 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_23_0_0_7);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_114 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_23_0_0_6_0_0_2);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_115 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_24_0_0_1);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_116 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_24_0_0_2_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_117 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_25_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_118 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_24_0_0_2_0_0_2_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_119 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_24_0_0_2_0_0_3);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_120 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedCsString(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_25_0_0_1_0_0_0);
	public final static org.emftext.sdk.concretesyntax.resource.cs.ICsExpectedElement TERMINAL_121 = new org.emftext.sdk.concretesyntax.resource.cs.mopp.CsExpectedStructuralFeature(org.emftext.sdk.concretesyntax.resource.cs.grammar.CsGrammarInformationProvider.CS_25_0_0_1_0_0_1);
	
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_0 = org.emftext.sdk.concretesyntax.ConcretesyntaxPackage.eINSTANCE.getAnnotable().getEStructuralFeature(org.emftext.sdk.concretesyntax.ConcretesyntaxPackage.ANNOTABLE__ANNOTATIONS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_1 = org.emftext.sdk.concretesyntax.ConcretesyntaxPackage.eINSTANCE.getConcreteSyntax().getEStructuralFeature(org.emftext.sdk.concretesyntax.ConcretesyntaxPackage.CONCRETE_SYNTAX__IMPORTS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_2 = org.emftext.sdk.concretesyntax.ConcretesyntaxPackage.eINSTANCE.getConcreteSyntax().getEStructuralFeature(org.emftext.sdk.concretesyntax.ConcretesyntaxPackage.CONCRETE_SYNTAX__OPTIONS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_3 = org.emftext.sdk.concretesyntax.ConcretesyntaxPackage.eINSTANCE.getConcreteSyntax().getEStructuralFeature(org.emftext.sdk.concretesyntax.ConcretesyntaxPackage.CONCRETE_SYNTAX__TOKENS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_4 = org.emftext.sdk.concretesyntax.ConcretesyntaxPackage.eINSTANCE.getConcreteSyntax().getEStructuralFeature(org.emftext.sdk.concretesyntax.ConcretesyntaxPackage.CONCRETE_SYNTAX__TOKEN_STYLES);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_5 = org.emftext.sdk.concretesyntax.ConcretesyntaxPackage.eINSTANCE.getConcreteSyntax().getEStructuralFeature(org.emftext.sdk.concretesyntax.ConcretesyntaxPackage.CONCRETE_SYNTAX__RULES);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_6 = org.emftext.sdk.concretesyntax.ConcretesyntaxPackage.eINSTANCE.getSyntaxElement().getEStructuralFeature(org.emftext.sdk.concretesyntax.ConcretesyntaxPackage.SYNTAX_ELEMENT__CHILDREN);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_7 = org.emftext.sdk.concretesyntax.ConcretesyntaxPackage.eINSTANCE.getEnumTerminal().getEStructuralFeature(org.emftext.sdk.concretesyntax.ConcretesyntaxPackage.ENUM_TERMINAL__LITERALS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_8 = org.emftext.sdk.concretesyntax.ConcretesyntaxPackage.eINSTANCE.getRegexComposite().getEStructuralFeature(org.emftext.sdk.concretesyntax.ConcretesyntaxPackage.REGEX_COMPOSITE__REGEX_PARTS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_9 = org.emftext.sdk.concretesyntax.ConcretesyntaxPackage.eINSTANCE.getAnnotation().getEStructuralFeature(org.emftext.sdk.concretesyntax.ConcretesyntaxPackage.ANNOTATION__PARAMETERS);
	
	public final static org.eclipse.emf.ecore.EStructuralFeature[] EMPTY_FEATURE_ARRAY = new org.eclipse.emf.ecore.EStructuralFeature[0];
	
	public static void wire0() {
		TERMINAL_1.addFollower(TERMINAL_2, EMPTY_FEATURE_ARRAY);
		TERMINAL_2.addFollower(TERMINAL_3, EMPTY_FEATURE_ARRAY);
		TERMINAL_3.addFollower(TERMINAL_4, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_5, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_6, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_7, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_8, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_9, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_10, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_11, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_12, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_7, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_8, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_9, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_10, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_11, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_12, EMPTY_FEATURE_ARRAY);
		TERMINAL_7.addFollower(TERMINAL_13, EMPTY_FEATURE_ARRAY);
		TERMINAL_13.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_13.addFollower(TERMINAL_8, EMPTY_FEATURE_ARRAY);
		TERMINAL_13.addFollower(TERMINAL_9, EMPTY_FEATURE_ARRAY);
		TERMINAL_13.addFollower(TERMINAL_10, EMPTY_FEATURE_ARRAY);
		TERMINAL_13.addFollower(TERMINAL_11, EMPTY_FEATURE_ARRAY);
		TERMINAL_13.addFollower(TERMINAL_12, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_15, EMPTY_FEATURE_ARRAY);
		TERMINAL_15.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_15.addFollower(TERMINAL_8, EMPTY_FEATURE_ARRAY);
		TERMINAL_15.addFollower(TERMINAL_9, EMPTY_FEATURE_ARRAY);
		TERMINAL_15.addFollower(TERMINAL_10, EMPTY_FEATURE_ARRAY);
		TERMINAL_15.addFollower(TERMINAL_11, EMPTY_FEATURE_ARRAY);
		TERMINAL_15.addFollower(TERMINAL_12, EMPTY_FEATURE_ARRAY);
		TERMINAL_8.addFollower(TERMINAL_16, EMPTY_FEATURE_ARRAY);
		TERMINAL_16.addFollower(TERMINAL_17, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_16.addFollower(TERMINAL_18, EMPTY_FEATURE_ARRAY);
		TERMINAL_18.addFollower(TERMINAL_9, EMPTY_FEATURE_ARRAY);
		TERMINAL_18.addFollower(TERMINAL_10, EMPTY_FEATURE_ARRAY);
		TERMINAL_18.addFollower(TERMINAL_11, EMPTY_FEATURE_ARRAY);
		TERMINAL_18.addFollower(TERMINAL_12, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_19.addFollower(TERMINAL_20, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_19.addFollower(TERMINAL_21, EMPTY_FEATURE_ARRAY);
		TERMINAL_22.addFollower(TERMINAL_20, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_22.addFollower(TERMINAL_21, EMPTY_FEATURE_ARRAY);
		TERMINAL_21.addFollower(TERMINAL_10, EMPTY_FEATURE_ARRAY);
		TERMINAL_21.addFollower(TERMINAL_11, EMPTY_FEATURE_ARRAY);
		TERMINAL_21.addFollower(TERMINAL_12, EMPTY_FEATURE_ARRAY);
		TERMINAL_10.addFollower(TERMINAL_23, EMPTY_FEATURE_ARRAY);
		TERMINAL_23.addFollower(TERMINAL_0, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_3, });
		TERMINAL_23.addFollower(TERMINAL_24, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_23.addFollower(TERMINAL_25, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_23.addFollower(TERMINAL_26, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_23.addFollower(TERMINAL_27, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_23.addFollower(TERMINAL_28, EMPTY_FEATURE_ARRAY);
		TERMINAL_29.addFollower(TERMINAL_0, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_3, });
		TERMINAL_29.addFollower(TERMINAL_24, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_29.addFollower(TERMINAL_25, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_29.addFollower(TERMINAL_26, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_29.addFollower(TERMINAL_27, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_29.addFollower(TERMINAL_28, EMPTY_FEATURE_ARRAY);
		TERMINAL_28.addFollower(TERMINAL_11, EMPTY_FEATURE_ARRAY);
		TERMINAL_28.addFollower(TERMINAL_12, EMPTY_FEATURE_ARRAY);
		TERMINAL_11.addFollower(TERMINAL_30, EMPTY_FEATURE_ARRAY);
		TERMINAL_30.addFollower(TERMINAL_31, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_30.addFollower(TERMINAL_32, EMPTY_FEATURE_ARRAY);
		TERMINAL_32.addFollower(TERMINAL_12, EMPTY_FEATURE_ARRAY);
		TERMINAL_12.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
		TERMINAL_33.addFollower(TERMINAL_0, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_5, });
		TERMINAL_33.addFollower(TERMINAL_34, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_33.addFollower(TERMINAL_35, EMPTY_FEATURE_ARRAY);
		TERMINAL_17.addFollower(TERMINAL_36, EMPTY_FEATURE_ARRAY);
		TERMINAL_36.addFollower(TERMINAL_37, EMPTY_FEATURE_ARRAY);
		TERMINAL_37.addFollower(TERMINAL_38, EMPTY_FEATURE_ARRAY);
		TERMINAL_37.addFollower(TERMINAL_39, EMPTY_FEATURE_ARRAY);
		TERMINAL_37.addFollower(TERMINAL_17, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_37.addFollower(TERMINAL_18, EMPTY_FEATURE_ARRAY);
		TERMINAL_38.addFollower(TERMINAL_39, EMPTY_FEATURE_ARRAY);
		TERMINAL_38.addFollower(TERMINAL_17, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_38.addFollower(TERMINAL_18, EMPTY_FEATURE_ARRAY);
		TERMINAL_39.addFollower(TERMINAL_40, EMPTY_FEATURE_ARRAY);
		TERMINAL_40.addFollower(TERMINAL_41, EMPTY_FEATURE_ARRAY);
		TERMINAL_41.addFollower(TERMINAL_42, EMPTY_FEATURE_ARRAY);
		TERMINAL_41.addFollower(TERMINAL_17, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_41.addFollower(TERMINAL_18, EMPTY_FEATURE_ARRAY);
		TERMINAL_42.addFollower(TERMINAL_17, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_42.addFollower(TERMINAL_18, EMPTY_FEATURE_ARRAY);
		TERMINAL_20.addFollower(TERMINAL_43, EMPTY_FEATURE_ARRAY);
		TERMINAL_43.addFollower(TERMINAL_44, EMPTY_FEATURE_ARRAY);
		TERMINAL_44.addFollower(TERMINAL_22, EMPTY_FEATURE_ARRAY);
		TERMINAL_34.addFollower(TERMINAL_45, EMPTY_FEATURE_ARRAY);
		TERMINAL_45.addFollower(TERMINAL_46, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, FEATURE_6, });
		TERMINAL_45.addFollower(TERMINAL_47, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, FEATURE_6, });
		TERMINAL_45.addFollower(TERMINAL_48, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, FEATURE_6, });
		TERMINAL_45.addFollower(TERMINAL_49, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, FEATURE_6, });
		TERMINAL_45.addFollower(TERMINAL_50, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, FEATURE_6, });
		TERMINAL_45.addFollower(TERMINAL_51, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, FEATURE_6, });
		TERMINAL_45.addFollower(TERMINAL_52, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, FEATURE_6, });
		TERMINAL_45.addFollower(TERMINAL_53, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, FEATURE_6, });
		TERMINAL_45.addFollower(TERMINAL_54, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, FEATURE_6, });
		TERMINAL_45.addFollower(TERMINAL_55, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, FEATURE_6, });
		TERMINAL_56.addFollower(TERMINAL_0, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, FEATURE_5, });
		TERMINAL_56.addFollower(TERMINAL_34, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_56.addFollower(TERMINAL_35, EMPTY_FEATURE_ARRAY);
		TERMINAL_57.addFollower(TERMINAL_46, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, });
		TERMINAL_57.addFollower(TERMINAL_47, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, });
		TERMINAL_57.addFollower(TERMINAL_48, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, });
		TERMINAL_57.addFollower(TERMINAL_49, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, });
		TERMINAL_57.addFollower(TERMINAL_50, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, });
		TERMINAL_57.addFollower(TERMINAL_51, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, });
		TERMINAL_57.addFollower(TERMINAL_52, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, });
		TERMINAL_57.addFollower(TERMINAL_53, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, });
		TERMINAL_57.addFollower(TERMINAL_54, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, });
		TERMINAL_57.addFollower(TERMINAL_55, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, });
		TERMINAL_46.addFollower(TERMINAL_46, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_46.addFollower(TERMINAL_47, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_46.addFollower(TERMINAL_48, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_46.addFollower(TERMINAL_49, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_46.addFollower(TERMINAL_50, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_46.addFollower(TERMINAL_51, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_46.addFollower(TERMINAL_52, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_46.addFollower(TERMINAL_53, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_46.addFollower(TERMINAL_54, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_46.addFollower(TERMINAL_55, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_46.addFollower(TERMINAL_57, EMPTY_FEATURE_ARRAY);
		TERMINAL_46.addFollower(TERMINAL_56, EMPTY_FEATURE_ARRAY);
		TERMINAL_46.addFollower(TERMINAL_58, EMPTY_FEATURE_ARRAY);
		TERMINAL_47.addFollower(TERMINAL_59, EMPTY_FEATURE_ARRAY);
		TERMINAL_59.addFollower(TERMINAL_60, EMPTY_FEATURE_ARRAY);
		TERMINAL_60.addFollower(TERMINAL_61, EMPTY_FEATURE_ARRAY);
		TERMINAL_61.addFollower(TERMINAL_62, EMPTY_FEATURE_ARRAY);
		TERMINAL_48.addFollower(TERMINAL_63, EMPTY_FEATURE_ARRAY);
		TERMINAL_63.addFollower(TERMINAL_64, EMPTY_FEATURE_ARRAY);
		TERMINAL_64.addFollower(TERMINAL_65, EMPTY_FEATURE_ARRAY);
		TERMINAL_49.addFollower(TERMINAL_66, EMPTY_FEATURE_ARRAY);
		TERMINAL_66.addFollower(TERMINAL_67, EMPTY_FEATURE_ARRAY);
		TERMINAL_67.addFollower(TERMINAL_68, EMPTY_FEATURE_ARRAY);
		TERMINAL_68.addFollower(TERMINAL_69, EMPTY_FEATURE_ARRAY);
		TERMINAL_69.addFollower(TERMINAL_70, EMPTY_FEATURE_ARRAY);
		TERMINAL_69.addFollower(TERMINAL_71, EMPTY_FEATURE_ARRAY);
		TERMINAL_70.addFollower(TERMINAL_72, EMPTY_FEATURE_ARRAY);
		TERMINAL_72.addFollower(TERMINAL_71, EMPTY_FEATURE_ARRAY);
		TERMINAL_71.addFollower(TERMINAL_73, EMPTY_FEATURE_ARRAY);
		TERMINAL_50.addFollower(TERMINAL_74, EMPTY_FEATURE_ARRAY);
		TERMINAL_74.addFollower(TERMINAL_75, EMPTY_FEATURE_ARRAY);
		TERMINAL_75.addFollower(TERMINAL_76, EMPTY_FEATURE_ARRAY);
		TERMINAL_76.addFollower(TERMINAL_77, EMPTY_FEATURE_ARRAY);
		TERMINAL_77.addFollower(TERMINAL_78, EMPTY_FEATURE_ARRAY);
		TERMINAL_78.addFollower(TERMINAL_79, EMPTY_FEATURE_ARRAY);
		TERMINAL_51.addFollower(TERMINAL_80, EMPTY_FEATURE_ARRAY);
		TERMINAL_80.addFollower(TERMINAL_81, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_82.addFollower(TERMINAL_81, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_83.addFollower(TERMINAL_84, EMPTY_FEATURE_ARRAY);
		TERMINAL_81.addFollower(TERMINAL_85, EMPTY_FEATURE_ARRAY);
		TERMINAL_85.addFollower(TERMINAL_86, EMPTY_FEATURE_ARRAY);
		TERMINAL_86.addFollower(TERMINAL_82, EMPTY_FEATURE_ARRAY);
		TERMINAL_86.addFollower(TERMINAL_83, EMPTY_FEATURE_ARRAY);
		TERMINAL_52.addFollower(TERMINAL_87, EMPTY_FEATURE_ARRAY);
		TERMINAL_52.addFollower(TERMINAL_88, EMPTY_FEATURE_ARRAY);
		TERMINAL_87.addFollower(TERMINAL_89, EMPTY_FEATURE_ARRAY);
		TERMINAL_89.addFollower(TERMINAL_90, EMPTY_FEATURE_ARRAY);
		TERMINAL_89.addFollower(TERMINAL_88, EMPTY_FEATURE_ARRAY);
		TERMINAL_90.addFollower(TERMINAL_91, EMPTY_FEATURE_ARRAY);
		TERMINAL_91.addFollower(TERMINAL_90, EMPTY_FEATURE_ARRAY);
		TERMINAL_91.addFollower(TERMINAL_88, EMPTY_FEATURE_ARRAY);
		TERMINAL_53.addFollower(TERMINAL_46, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, FEATURE_6, });
		TERMINAL_53.addFollower(TERMINAL_47, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, FEATURE_6, });
		TERMINAL_53.addFollower(TERMINAL_48, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, FEATURE_6, });
		TERMINAL_53.addFollower(TERMINAL_49, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, FEATURE_6, });
		TERMINAL_53.addFollower(TERMINAL_50, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, FEATURE_6, });
		TERMINAL_53.addFollower(TERMINAL_51, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, FEATURE_6, });
		TERMINAL_53.addFollower(TERMINAL_52, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, FEATURE_6, });
		TERMINAL_53.addFollower(TERMINAL_53, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, FEATURE_6, });
		TERMINAL_53.addFollower(TERMINAL_54, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, FEATURE_6, });
		TERMINAL_53.addFollower(TERMINAL_55, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, FEATURE_6, FEATURE_6, });
		TERMINAL_58.addFollower(TERMINAL_92, EMPTY_FEATURE_ARRAY);
		TERMINAL_54.addFollower(TERMINAL_46, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_54.addFollower(TERMINAL_47, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_54.addFollower(TERMINAL_48, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_54.addFollower(TERMINAL_49, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_54.addFollower(TERMINAL_50, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_54.addFollower(TERMINAL_51, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_54.addFollower(TERMINAL_52, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_54.addFollower(TERMINAL_53, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_54.addFollower(TERMINAL_54, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_54.addFollower(TERMINAL_55, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_54.addFollower(TERMINAL_57, EMPTY_FEATURE_ARRAY);
		TERMINAL_54.addFollower(TERMINAL_56, EMPTY_FEATURE_ARRAY);
		TERMINAL_54.addFollower(TERMINAL_58, EMPTY_FEATURE_ARRAY);
		TERMINAL_55.addFollower(TERMINAL_46, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_55.addFollower(TERMINAL_47, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_55.addFollower(TERMINAL_48, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_55.addFollower(TERMINAL_49, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_55.addFollower(TERMINAL_50, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_55.addFollower(TERMINAL_51, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_55.addFollower(TERMINAL_52, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_55.addFollower(TERMINAL_53, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_55.addFollower(TERMINAL_54, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_55.addFollower(TERMINAL_55, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_55.addFollower(TERMINAL_57, EMPTY_FEATURE_ARRAY);
		TERMINAL_55.addFollower(TERMINAL_56, EMPTY_FEATURE_ARRAY);
		TERMINAL_55.addFollower(TERMINAL_58, EMPTY_FEATURE_ARRAY);
		TERMINAL_24.addFollower(TERMINAL_93, EMPTY_FEATURE_ARRAY);
		TERMINAL_93.addFollower(TERMINAL_94, EMPTY_FEATURE_ARRAY);
		TERMINAL_94.addFollower(TERMINAL_95, EMPTY_FEATURE_ARRAY);
		TERMINAL_95.addFollower(TERMINAL_96, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_95.addFollower(TERMINAL_97, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_98.addFollower(TERMINAL_96, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_98.addFollower(TERMINAL_97, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_25.addFollower(TERMINAL_99, EMPTY_FEATURE_ARRAY);
		TERMINAL_99.addFollower(TERMINAL_96, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_99.addFollower(TERMINAL_97, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_100.addFollower(TERMINAL_96, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_100.addFollower(TERMINAL_97, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_101.addFollower(TERMINAL_102, EMPTY_FEATURE_ARRAY);
		TERMINAL_102.addFollower(TERMINAL_103, EMPTY_FEATURE_ARRAY);
		TERMINAL_103.addFollower(TERMINAL_29, EMPTY_FEATURE_ARRAY);
		TERMINAL_26.addFollower(TERMINAL_104, EMPTY_FEATURE_ARRAY);
		TERMINAL_104.addFollower(TERMINAL_105, EMPTY_FEATURE_ARRAY);
		TERMINAL_105.addFollower(TERMINAL_96, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_105.addFollower(TERMINAL_97, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_106.addFollower(TERMINAL_96, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_106.addFollower(TERMINAL_97, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_27.addFollower(TERMINAL_107, EMPTY_FEATURE_ARRAY);
		TERMINAL_107.addFollower(TERMINAL_29, EMPTY_FEATURE_ARRAY);
		TERMINAL_96.addFollower(TERMINAL_98, EMPTY_FEATURE_ARRAY);
		TERMINAL_96.addFollower(TERMINAL_29, EMPTY_FEATURE_ARRAY);
		TERMINAL_96.addFollower(TERMINAL_100, EMPTY_FEATURE_ARRAY);
		TERMINAL_96.addFollower(TERMINAL_101, EMPTY_FEATURE_ARRAY);
		TERMINAL_96.addFollower(TERMINAL_106, EMPTY_FEATURE_ARRAY);
		TERMINAL_97.addFollower(TERMINAL_98, EMPTY_FEATURE_ARRAY);
		TERMINAL_97.addFollower(TERMINAL_29, EMPTY_FEATURE_ARRAY);
		TERMINAL_97.addFollower(TERMINAL_100, EMPTY_FEATURE_ARRAY);
		TERMINAL_97.addFollower(TERMINAL_101, EMPTY_FEATURE_ARRAY);
		TERMINAL_97.addFollower(TERMINAL_106, EMPTY_FEATURE_ARRAY);
		TERMINAL_31.addFollower(TERMINAL_108, EMPTY_FEATURE_ARRAY);
		TERMINAL_31.addFollower(TERMINAL_109, EMPTY_FEATURE_ARRAY);
		TERMINAL_108.addFollower(TERMINAL_110, EMPTY_FEATURE_ARRAY);
		TERMINAL_110.addFollower(TERMINAL_108, EMPTY_FEATURE_ARRAY);
		TERMINAL_110.addFollower(TERMINAL_109, EMPTY_FEATURE_ARRAY);
		TERMINAL_109.addFollower(TERMINAL_111, EMPTY_FEATURE_ARRAY);
		TERMINAL_111.addFollower(TERMINAL_112, EMPTY_FEATURE_ARRAY);
		TERMINAL_111.addFollower(TERMINAL_113, EMPTY_FEATURE_ARRAY);
		TERMINAL_112.addFollower(TERMINAL_114, EMPTY_FEATURE_ARRAY);
		TERMINAL_114.addFollower(TERMINAL_112, EMPTY_FEATURE_ARRAY);
		TERMINAL_114.addFollower(TERMINAL_113, EMPTY_FEATURE_ARRAY);
		TERMINAL_113.addFollower(TERMINAL_31, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_113.addFollower(TERMINAL_32, EMPTY_FEATURE_ARRAY);
		TERMINAL_0.addFollower(TERMINAL_115, EMPTY_FEATURE_ARRAY);
		TERMINAL_115.addFollower(TERMINAL_116, EMPTY_FEATURE_ARRAY);
		TERMINAL_115.addFollower(TERMINAL_0, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_115.addFollower(TERMINAL_1, EMPTY_FEATURE_ARRAY);
		TERMINAL_115.addFollower(TERMINAL_2, EMPTY_FEATURE_ARRAY);
		TERMINAL_115.addFollower(TERMINAL_34, EMPTY_FEATURE_ARRAY);
		TERMINAL_115.addFollower(TERMINAL_24, EMPTY_FEATURE_ARRAY);
		TERMINAL_115.addFollower(TERMINAL_25, EMPTY_FEATURE_ARRAY);
		TERMINAL_116.addFollower(TERMINAL_117, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, });
		TERMINAL_118.addFollower(TERMINAL_117, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, });
		TERMINAL_119.addFollower(TERMINAL_0, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_119.addFollower(TERMINAL_1, EMPTY_FEATURE_ARRAY);
		TERMINAL_119.addFollower(TERMINAL_2, EMPTY_FEATURE_ARRAY);
		TERMINAL_119.addFollower(TERMINAL_34, EMPTY_FEATURE_ARRAY);
		TERMINAL_119.addFollower(TERMINAL_24, EMPTY_FEATURE_ARRAY);
		TERMINAL_119.addFollower(TERMINAL_25, EMPTY_FEATURE_ARRAY);
		TERMINAL_117.addFollower(TERMINAL_120, EMPTY_FEATURE_ARRAY);
		TERMINAL_117.addFollower(TERMINAL_118, EMPTY_FEATURE_ARRAY);
		TERMINAL_117.addFollower(TERMINAL_119, EMPTY_FEATURE_ARRAY);
		TERMINAL_120.addFollower(TERMINAL_121, EMPTY_FEATURE_ARRAY);
		TERMINAL_121.addFollower(TERMINAL_118, EMPTY_FEATURE_ARRAY);
		TERMINAL_121.addFollower(TERMINAL_119, EMPTY_FEATURE_ARRAY);
	}
	// wire the terminals
	static {
		wire0();
	}
}
