package owl owl "http://org.emftext/owl.ecore" {

	abstract class IRIIdentified {
			unique ordered changeable iD attribute EString iri (1..1);
	}
	
	abstract class URIIdentified {
			unique ordered changeable attribute EString uri (1..1);
	}
	
	abstract class Annotateable {
			containment unique ordered changeable resolveProxies reference Annotation annotations (0..-1);
	}
	
	 class Ontology  extends URIIdentified, Annotateable {
			unique ordered changeable attribute EString versionIRI (0..1);
			unique ordered changeable resolveProxies reference Ontology imports (0..-1);
			containment unique ordered changeable resolveProxies reference Frame frames (0..-1);
	}
	
	 class OntologyDocument {
			containment unique ordered changeable resolveProxies reference Ontology ontology (1..1);
			containment unique ordered changeable resolveProxies reference Namespace namespace (0..-1);
	}
	
	 class Annotation  extends Annotateable {
			unique ordered changeable resolveProxies reference AnnotationProperty annotationProperty (1..-1);
			containment unique ordered changeable resolveProxies reference Target target (1..-1);
	}
	
	abstract class Target {
	}
	
	 class IRITarget   extends Target {
			unique ordered changeable resolveProxies reference IRIIdentified target (1..1);
	}
	
	 class LiteralTarget  extends Target {
			containment unique ordered changeable resolveProxies reference Literal literal (1..1);
	}
	
	 class Namespace  extends URIIdentified {
			unique ordered changeable attribute EString prefix (1..1);
	}
	
	abstract class Frame  extends IRIIdentified {
	}
	
	abstract class Feature  extends Frame {
	}
	
	 class DataProperty  extends Feature, Annotateable {
			containment unique ordered changeable resolveProxies reference Description domain (0..-1);
			containment unique ordered changeable resolveProxies reference DataRange range (0..-1);
			unique ordered changeable attribute Characteristic characteristic (0..1);
			unique ordered changeable resolveProxies reference DataProperty superProperties (0..-1);
			unique ordered changeable resolveProxies reference DataProperty equivalentProperties (0..-1);
			unique ordered changeable resolveProxies reference DataProperty disjointProperties (0..-1);
	}
	
	 class AnnotationProperty  extends Frame, Annotateable {
			unique ordered changeable resolveProxies reference IRIIdentified domains (0..-1);
			unique ordered changeable resolveProxies reference IRIIdentified ranges (0..-1);
			unique ordered changeable resolveProxies reference AnnotationProperty superAnnotationProperties (0..-1);
	}
	
	 class Class  extends Frame, Annotateable {
			containment unique ordered changeable resolveProxies reference Description superClassesDescriptions (0..-1);
			containment unique ordered changeable resolveProxies reference Description equivalentClassesDescriptions (0..-1);
			containment unique ordered changeable resolveProxies reference Description disjointWithClassesDescriptions (0..-1);
			containment unique ordered changeable resolveProxies reference Description disjointUnionWithClassesDescriptions (0..-1);
	}
	
	 class ObjectProperty  extends Feature, Annotateable {
			containment unique ordered changeable resolveProxies reference Description propertyDomain (0..-1);
			containment unique ordered changeable resolveProxies reference Description propertyRange (0..-1);
			unique ordered changeable attribute Characteristic characteristics (0..-1);
			containment unique ordered changeable resolveProxies reference ObjectPropertyReference superProperties (0..-1);
			containment unique ordered changeable resolveProxies reference ObjectPropertyReference equivalentProperties (0..-1);
			containment unique ordered changeable resolveProxies reference ObjectPropertyReference disjointProperties (0..-1);
			containment unique ordered changeable resolveProxies reference ObjectPropertyReference inverseProperties (0..-1);
			containment unique ordered changeable resolveProxies reference ObjectPropertyReference subPropertyChains (0..-1);
	}
	
	 class Individual  extends Frame, Annotateable {
			containment unique ordered changeable resolveProxies reference Description types (0..-1);
			containment unique ordered changeable resolveProxies reference Fact facts (0..-1);
			unique ordered changeable resolveProxies reference Individual sameAs (0..-1);
			unique ordered changeable resolveProxies reference Individual differentFrom (0..-1);
	}
	
	 class Datatype  extends Frame, Annotateable {
			containment unique ordered changeable resolveProxies reference DataRange dataRange (0..1);
	}
	
	abstract class Misc  extends Frame, Annotateable {
	}
	
	 class EquivalentClasses  extends Misc {
			containment unique ordered changeable resolveProxies reference Description descriptions (1..-1);
	}
	
	 class DisjointClasses  extends Misc {
			containment unique ordered changeable resolveProxies reference Description descriptions (1..-1);
	}
	
	 class EquivalentProperties  extends Misc {
			unique ordered changeable resolveProxies reference ObjectProperty objectProperties (1..-1);
	}
	
	 class DisjointProperties  extends Misc {
			unique ordered changeable resolveProxies reference ObjectProperty objectProperties (1..-1);
	}
	
	 class SameIndividuals  extends Misc {
			unique ordered changeable resolveProxies reference Individual individuals (1..-1);
	}
	
	 class DifferentIndividuals  extends Misc {
			unique ordered changeable resolveProxies reference Individual individuals (1..-1);
	}
	
	 class HasKey  extends Misc {
			unique ordered changeable attribute EBoolean inverse (1..1);
			containment unique ordered changeable resolveProxies reference Description description (1..1);
			unique ordered changeable resolveProxies reference Feature feature (0..-1);
	}
	
	 class DataRange {
			containment unique ordered changeable resolveProxies reference DataConjunction dataConjunctions (1..-1);
	}
	
	 class DataConjunction  extends DataRange {
			containment unique ordered changeable resolveProxies reference DataPrimary dataPrimaries (1..-1);
	}
	
	abstract class DataPrimary  extends DataRange {
			unique ordered changeable attribute EBoolean not (1..1);
	}
	
	 class DatatypeReference  extends DataPrimary {
			unique ordered changeable resolveProxies reference Datatype theDatatype (1..1);
			containment unique ordered changeable resolveProxies reference Facet facets (0..-1);
	}
	
	 class Facet {
			unique ordered changeable attribute FacetType facetType (1..1);
			containment unique ordered changeable resolveProxies reference Literal literal (1..1);
	}
	serializable enum FacetType {
			1 : LENGTH = "length";
			2 : MIN_LENGTH = "minLength";
			3 : MAX_LENGTH = "maxLength";
			4 : PATTERN = "pattern";
			5 : LANG_PATTERN = "langPattern";
			6 : LESS_EQUALS = "<=";
			7 : LESS = "<";
			8 : GREATER = ">";
			9 : GREATER_EQUALS = ">=";
}

	 class NestedDataRange  extends DataPrimary {
			containment unique ordered changeable resolveProxies reference DataRange dataRange (1..1);
	}
	
	 class DataPrimaryLiterals  extends DataPrimary {
			containment unique ordered changeable resolveProxies reference Literal literals (1..-1);
	}
	
	abstract class Fact {
			unique ordered changeable attribute EBoolean not (1..1);
	}
	
	 class ObjectPropertyFact  extends Fact {
			unique ordered changeable resolveProxies reference ObjectProperty objectProperty (1..1);
			unique ordered changeable resolveProxies reference Individual individual (1..1);
	}
	
	 class DataPropertyFact  extends Fact {
			unique ordered changeable resolveProxies reference DataProperty dataProperty (1..1);
			containment unique ordered changeable resolveProxies reference Literal literal (1..1);
	}
	serializable enum Characteristic {
			1 : FUNCTIONAL = "Functional";
			2 : INVERSE_FUNCTIONAL = "InverseFunctional";
			3 : REFLEXIVE = "Reflexive";
			4 : IRREFLEXIVE = "Irreflexive";
			5 : SYMETRIC = "Symmetric";
			6 : ASYMETRIC = "Asymmetric";
			7 : TRANSITIVE = "Transitive";
}

	abstract class Description  extends Annotateable {
	}
	
	 class Disjunction  extends Description {
			containment unique ordered changeable resolveProxies reference Description conjunctions (1..-1);
	}
	
	 class Conjunction  extends Description {
			unique ordered changeable resolveProxies reference Class clazz (0..1);
			containment unique ordered changeable resolveProxies reference Description primaries (0..-1);
	}
	
	abstract class Primary  extends Description {
			unique ordered changeable attribute EBoolean not (1..1);
	}
	
	 class IndividualsAtomic  extends Primary {
			unique ordered changeable resolveProxies reference Individual individuals (0..-1);
	}
	
	 class ClassAtomic  extends Primary {
			unique ordered changeable resolveProxies reference Class clazz (1..1);
	}
	
	 class NestedDescription  extends Primary {
			containment unique ordered changeable resolveProxies reference Description description (1..1);
	}
	
	abstract class FeatureRestriction  extends Primary {
			unique ordered changeable attribute EBoolean inverse (1..1);
			unique ordered changeable resolveProxies reference Feature feature (1..1);
	}
	
	abstract class ObjectPropertyRestriction  extends Primary {
			unique ordered changeable attribute EBoolean inverse (1..1);
			unique ordered changeable resolveProxies reference ObjectProperty objectProperty (1..1);
	}
	
	 class ObjectPropertyReference {
			unique ordered changeable resolveProxies reference ObjectProperty objectProperty (1..1);
			unique ordered changeable attribute EBoolean inverse (1..1);
	}
	
	 class ObjectPropertySome  extends FeatureRestriction {
			containment unique ordered changeable resolveProxies reference Primary primary (0..1);
			containment unique ordered changeable resolveProxies reference DataPrimary dataPrimary (0..1);
	}
	
	 class ObjectPropertyOnly  extends FeatureRestriction {
			containment unique ordered changeable resolveProxies reference Primary primary (0..1);
			containment unique ordered changeable resolveProxies reference DataPrimary dataPrimary (0..1);
	}
	
	 class ObjectPropertyValue  extends FeatureRestriction {
			unique ordered changeable resolveProxies reference Individual individual (0..1);
			containment unique ordered changeable resolveProxies reference Literal literal (0..1);
	}
	
	 class ObjectPropertySelf  extends ObjectPropertyRestriction {
	}
	
	 class ObjectPropertyMin  extends FeatureRestriction {
			containment unique ordered changeable resolveProxies reference Primary primary (0..1);
			containment unique ordered changeable resolveProxies reference DataPrimary dataPrimary (0..1);
			unique ordered changeable attribute EInt value (1..1);
	}
	
	 class ObjectPropertyMax  extends FeatureRestriction {
			containment unique ordered changeable resolveProxies reference Primary primary (0..1);
			containment unique ordered changeable resolveProxies reference DataPrimary dataPrimary (0..1);
			unique ordered changeable attribute EInt value (1..1);
	}
	
	 class ObjectPropertyExactly  extends FeatureRestriction {
			containment unique ordered changeable resolveProxies reference Primary primary (0..1);
			containment unique ordered changeable resolveProxies reference DataPrimary dataPrimary (0..1);
			unique ordered changeable attribute EInt value (1..1);
	}
	
	abstract class Literal {
	}
	
	 class TypedLiteral  extends Literal {
			unique ordered changeable attribute EString lexicalValue (1..1);
			unique ordered changeable resolveProxies reference Datatype theDatatype (1..1);
	}
	
	 class AbbreviatedXSDStringLiteral  extends Literal {
			unique ordered changeable attribute EString value (1..1);
	}
	
	 class AbbreviatedRDFTextLiteral  extends Literal {
			unique ordered changeable attribute EString value (1..1);
			unique ordered changeable attribute EString languageTag (1..1);
	}
	
	 class IntegerLiteral  extends Literal {
			unique ordered changeable attribute EInt value (1..1);
	}
	
	 class DecimalLiteral  extends Literal {
			unique ordered changeable attribute EInt preComma (1..1);
			unique ordered changeable attribute EInt postComma (1..1);
	}
	
	 class FloatingPointLiteral extends Literal {
			unique ordered changeable attribute EFloat literal (1..1);
	}
	
}