<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jdt" nsURI="http://www.emftext.org/commons/jdt" nsPrefix="jdt">
  <eClassifiers xsi:type="ecore:EClass" name="JDTJavaClassifier">
    <eOperations name="getQualifiedName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="java.lang.StringBuilder qualifiedName = new java.lang.StringBuilder();&#xA;qualifiedName.append(getPackageName());&#xA;qualifiedName.append(&quot;.&quot;);&#xA;for ( java.lang.String enclosingType : getEnclosingTypeNames()) {&#xA;&#x9;qualifiedName.append(enclosingType);&#xA;&#x9;qualifiedName.append(&quot;$&quot;);&#xA;}&#xA;qualifiedName.append(getSimpleName());&#xA;return qualifiedName.toString();"/>
        <details key="documentation" value=""/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="simpleName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enclosingTypeNames" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
