<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="office2"
    nsURI="http://reuseware.org/coconut/office2" nsPrefix="org.emftext.language.office2">
  <eClassifiers xsi:type="ecore:EClass" name="Employee" eSuperTypes="#//OfficeElement">
    <eOperations name="removeYou"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentlyIn" ordered="false"
        lowerBound="1" eType="#//Room"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="worksIn" ordered="false"
        lowerBound="1" eType="#//Office"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="worksWith" ordered="false"
        upperBound="-1" eType="#//Employee"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LeisureRoom" eSuperTypes="#//Room">
    <eOperations name="removeYou"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eOperations name="removeYou"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OfficeElement" abstract="true" eSuperTypes="#//NamedElement">
    <eOperations name="removeYou"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="OfficeModel" ordered="false"
        eType="#//OfficeModel" eOpposite="#//OfficeModel/elements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OfficeModel" eSuperTypes="#//NamedElement">
    <eOperations name="assignToOffice"/>
    <eOperations name="relocate"/>
    <eOperations name="removeUnusedOffices">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="org.eclipse.emf.common.util.EList &lt; org.emftext.language.office2.Office >candidates = new org.eclipse.emf.common.util.BasicEList &lt; org.emftext.language.office2.Office >();&#xD;&#xA;for ( org.emftext.language.office2.OfficeElement element:getElements()) {&#xD;&#xA;&#x9;if (element instanceof org.emftext.language.office2.Office ) {&#xD;&#xA;&#x9;&#x9;candidates.add(( org.emftext.language.office2.Office ) element);&#xD;&#xA;&#x9;}&#xD;&#xA;}&#xD;&#xA;for ( org.emftext.language.office2.OfficeElement element:getElements()) {&#xD;&#xA;&#x9;if (element instanceof org.emftext.language.office2.Employee ) {&#xD;&#xA;&#x9;&#x9;if ((( org.emftext.language.office2.Employee ) element).getWorksIn() != null) {&#xD;&#xA;&#x9;&#x9;&#x9;candidates.remove((( org.emftext.language.office2.Employee ) element).getWorksIn());&#xD;&#xA;&#x9;&#x9;}&#xD;&#xA;&#x9;}&#xD;&#xA;}&#xD;&#xA;getElements().removeAll(candidates);&#xD;&#xA;"/>
        <details key="documentation" value=" Utility operation that removes all empty offices.&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="removeYou"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" ordered="false"
        upperBound="-1" eType="#//OfficeElement" containment="true" eOpposite="#//OfficeElement/OfficeModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Office" eSuperTypes="#//Room">
    <eOperations name="removeYou"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room" abstract="true" eSuperTypes="#//OfficeElement">
    <eOperations name="removeYou"/>
  </eClassifiers>
</ecore:EPackage>
