<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="enumtest2"
    nsURI="http://www.emftext.org/language/efactory/test/enumtest2" nsPrefix="enumtest2">
  <eClassifiers xsi:type="ecore:EClass" name="MyClass2">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="myAttribute" lowerBound="1"
        eType="ecore:EEnum enumtest.ecore#//MyEnum"/>
  </eClassifiers>
</ecore:EPackage>
