<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="extendingsyntax3"
    nsURI="http://www.emftext.org/test/extendingsyntax3" nsPrefix="extendingsyntax3">
  <eClassifiers xsi:type="ecore:EClass" name="E3">
    <eStructuralFeatures xsi:type="ecore:EReference" name="b1" lowerBound="1" eType="ecore:EClass basesyntax1.ecore#//B1"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="b3" lowerBound="1" eType="ecore:EClass basesyntax3.ecore#//B3"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
