<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="concretesyntax"
    nsURI="http://www.emftext.org/sdk/concretesyntax" nsPrefix="org.emftext.sdk.concretesyntax">
  <eClassifiers xsi:type="ecore:EClass" name="GenPackageDependentElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenPackage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageLocationHint" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteSyntax" eSuperTypes="#//GenPackageDependentElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifier" eType="#//Abstract"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startSymbols" lowerBound="1"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activeStartSymbols" lowerBound="1"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenClass"
        changeable="false" volatile="true" transient="true" derived="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allStartSymbols" lowerBound="1"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenClass"
        changeable="false" volatile="true" transient="true" derived="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1"
        eType="#//Option" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokens" upperBound="-1"
        eType="#//TokenDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="syntheticTokens" upperBound="-1"
        eType="#//TokenDefinition" transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokenStyles" upperBound="-1"
        eType="#//TokenStyle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allTokens" upperBound="-1"
        eType="#//TokenDefinition" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" lowerBound="1" upperBound="-1"
        eType="#//Rule" containment="true" eOpposite="#//Rule/syntax"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRules" lowerBound="1"
        upperBound="-1" eType="#//Rule" changeable="false" volatile="true" transient="true"
        derived="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import" eSuperTypes="#//GenPackageDependentElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concreteSyntax" eType="#//ConcreteSyntax"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="csLocationHint" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" lowerBound="1"
        eType="#//Choice" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaclass" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="syntax" lowerBound="1"
        eType="#//ConcreteSyntax" eOpposite="#//ConcreteSyntax/rules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Choice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" lowerBound="1"
        upperBound="-1" eType="#//Sequence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" lowerBound="1" upperBound="-1"
        eType="#//Definition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Definition" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CardinalityDefinition" abstract="true"
      eSuperTypes="#//Definition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cardinality" eType="#//Cardinality"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Terminal" abstract="true" eSuperTypes="#//CardinalityDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CsString" eSuperTypes="#//Definition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhiteSpaces" eSuperTypes="#//Definition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineBreak" eSuperTypes="#//Definition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tab" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cardinality" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PLUS" eSuperTypes="#//Cardinality"/>
  <eClassifiers xsi:type="ecore:EClass" name="STAR" eSuperTypes="#//Cardinality"/>
  <eClassifiers xsi:type="ecore:EClass" name="QUESTIONMARK" eSuperTypes="#//Cardinality"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompoundDefinition" eSuperTypes="#//CardinalityDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitions" eType="#//Choice"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TokenDefinition" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeReferences" upperBound="-1"
        eType="#//Placeholder" eOpposite="#//Placeholder/token"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="regex" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hidden" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="used" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NormalToken" eSuperTypes="#//TokenDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="QuotedToken" eSuperTypes="#//TokenDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suffix" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PredefinedToken" eSuperTypes="#//TokenDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Containment" eSuperTypes="#//Terminal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Placeholder" abstract="true" eSuperTypes="#//Terminal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="token" lowerBound="1" eType="#//TokenDefinition"
        eOpposite="#//TokenDefinition/attributeReferences"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlaceholderUsingSpecifiedToken" eSuperTypes="#//Placeholder"/>
  <eClassifiers xsi:type="ecore:EClass" name="PlaceholderUsingDefaultToken" eSuperTypes="#//Placeholder"/>
  <eClassifiers xsi:type="ecore:EClass" name="PlaceholderInQuotes" eSuperTypes="#//Placeholder">
    <eOperations name="getNormalizedPrefix" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eOperations name="getNormalizedSuffix" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suffix" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Option">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//OptionTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OptionTypes">
    <eLiterals name="GENERATE_TEST_ACTION" literal="generateTestAction"/>
    <eLiterals name="GENERATE_CODE_FROM_GENERATOR_MODEL" value="1" literal="generateCodeFromGeneratorModel"/>
    <eLiterals name="GENERATE_PRINTER_STUB_ONLY" value="2" literal="generatePrinterStubOnly"/>
    <eLiterals name="OVERRIDE_PLUGIN_XML" value="3" literal="overridePluginXML"/>
    <eLiterals name="OVERRIDE_MANIFEST" value="4" literal="overrideManifest"/>
    <eLiterals name="OVERRIDE_PARSER_SPEC" value="5" literal="overrideParserSpecification"/>
    <eLiterals name="OVERRIDE_TOKEN_RESOLVERS" value="6" literal="overrideTokenResolvers"/>
    <eLiterals name="OVERRIDE_REFERENCE_RESOLVERS" value="7" literal="overrideReferenceResolvers"/>
    <eLiterals name="OVERRIDE_REFERENCE_RESOLVER_SWITCH" value="8" literal="overrideReferenceResolverSwitch"/>
    <eLiterals name="OVERRIDE_TOKEN_RESOLVER_FACTORY" value="9" literal="overrideTokenResolverFactory"/>
    <eLiterals name="OVERRIDE_PRINTER" value="10" literal="overridePrinter"/>
    <eLiterals name="OVERRIDE_PRINTER_BASE" value="11" literal="overridePrinterBase"/>
    <eLiterals name="ANTLR_BACKTRACKING" value="12" literal="backtracking"/>
    <eLiterals name="ANTLR_MEMOIZE" value="13" literal="memoize"/>
    <eLiterals name="AUTOFIX_SIMPLE_LEFTRECURSION" value="14" literal="autofixSimpleLeftrecursion"/>
    <eLiterals name="FORCE_EOF" value="15" literal="forceEOF"/>
    <eLiterals name="DEFAULT_TOKEN_NAME" value="16" literal="defaultTokenName"/>
    <eLiterals name="USE_PREDEFINED_TOKENS" value="17" literal="usePredefinedTokens"/>
    <eLiterals name="TOKENSPACE" value="18" literal="tokenspace"/>
    <eLiterals name="RELOAD_GENERATOR_MODEL" value="19" literal="reloadGeneratorModel"/>
    <eLiterals name="OVERRIDE_DOT_CLASSPATH" value="20" literal="overrideClasspath"/>
    <eLiterals name="OVERRIDE_DOT_PROJECT" value="21" literal="overrideProjectFile"/>
    <eLiterals name="OVERRIDE_TEXT_RESOURCE" value="22" literal="overrideTextResource"/>
    <eLiterals name="OVERRIDE_RESOURCE_FACTORY" value="23" literal="overrideResourceFactory"/>
    <eLiterals name="OVERRIDE_NEW_FILE_WIZARD" value="24" literal="overrideNewFileWizard"/>
    <eLiterals name="PARSER_GENERATOR" value="25" literal="parserGenerator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Abstract"/>
  <eClassifiers xsi:type="ecore:EClass" name="TokenStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokenName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rgb" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fontStyles" upperBound="-1"
        eType="#//FontStyle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FontStyle">
    <eLiterals name="BOLD"/>
    <eLiterals name="ITALIC" value="1"/>
    <eLiterals name="STRIKETHROUGH" value="2"/>
    <eLiterals name="UNDERLINE" value="3"/>
  </eClassifiers>
</ecore:EPackage>
