package org.emftext.sdk.codegen.generators;

import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.io.PushbackReader;
import java.io.Reader;
import java.io.StringReader;
import java.io.StringWriter;
import java.net.URL;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.Set;
import java.util.Stack;
import java.util.Timer;
import java.util.TimerTask;
import java.util.regex.Matcher;

import javax.swing.event.DocumentListener;

import org.antlr.runtime.ANTLRStringStream;
import org.antlr.runtime.BitSet;
import org.antlr.runtime.CommonToken;
import org.antlr.runtime.EarlyExitException;
import org.antlr.runtime.FailedPredicateException;
import org.antlr.runtime.IntStream;
import org.antlr.runtime.Lexer;
import org.antlr.runtime.MismatchedNotSetException;
import org.antlr.runtime.MismatchedRangeException;
import org.antlr.runtime.MismatchedSetException;
import org.antlr.runtime.MismatchedTokenException;
import org.antlr.runtime.MismatchedTreeNodeException;
import org.antlr.runtime.NoViableAltException;
import org.antlr.runtime.RecognitionException;
import org.antlr.runtime.Token;
import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IMarker;
import org.eclipse.core.resources.IResource;
import org.eclipse.core.resources.IResourceChangeEvent;
import org.eclipse.core.resources.IResourceChangeListener;
import org.eclipse.core.resources.IResourceDelta;
import org.eclipse.core.resources.IResourceDeltaVisitor;
import org.eclipse.core.resources.IWorkspace;
import org.eclipse.core.resources.IWorkspaceRoot;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.core.runtime.Assert;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.IConfigurationElement;
import org.eclipse.core.runtime.IExtensionRegistry;
import org.eclipse.core.runtime.IPath;
import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.core.runtime.ListenerList;
import org.eclipse.core.runtime.Path;
import org.eclipse.core.runtime.Platform;
import org.eclipse.core.runtime.SafeRunner;
import org.eclipse.core.runtime.preferences.AbstractPreferenceInitializer;
import org.eclipse.emf.codegen.ecore.templates.editor.Editor;
import org.eclipse.emf.common.command.BasicCommandStack;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.impl.AdapterImpl;
import org.eclipse.emf.common.util.BasicEList;
import org.eclipse.emf.common.util.BasicEMap;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;
import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EEnumLiteral;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EOperation;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.emf.ecore.InternalEObject;
import org.eclipse.emf.ecore.impl.EObjectImpl;
import org.eclipse.emf.ecore.provider.EcoreItemProviderAdapterFactory;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.emf.ecore.resource.URIConverter;
import org.eclipse.emf.ecore.resource.Resource.Diagnostic;
import org.eclipse.emf.ecore.util.EObjectWithInverseResolvingEList;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.util.InternalEList;
import org.eclipse.emf.edit.domain.AdapterFactoryEditingDomain;
import org.eclipse.emf.edit.domain.EditingDomain;
import org.eclipse.emf.edit.domain.IEditingDomainProvider;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.ReflectiveItemProviderAdapterFactory;
import org.eclipse.emf.edit.provider.resource.ResourceItemProviderAdapterFactory;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryContentProvider;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.emf.edit.ui.provider.PropertyDescriptor;
import org.eclipse.emf.edit.ui.provider.PropertySource;
import org.eclipse.jface.action.Action;
import org.eclipse.jface.action.IAction;
import org.eclipse.jface.action.ToolBarManager;
import org.eclipse.jface.dialogs.IDialogConstants;
import org.eclipse.jface.dialogs.MessageDialog;
import org.eclipse.jface.preference.ColorSelector;
import org.eclipse.jface.preference.IPreferenceStore;
import org.eclipse.jface.preference.PreferenceConverter;
import org.eclipse.jface.preference.PreferencePage;
import org.eclipse.jface.resource.JFaceResources;
import org.eclipse.jface.text.AbstractInformationControl;
import org.eclipse.jface.text.AbstractReusableInformationControlCreator;
import org.eclipse.jface.text.BadLocationException;
import org.eclipse.jface.text.BadPositionCategoryException;
import org.eclipse.jface.text.DefaultInformationControl;
import org.eclipse.jface.text.Document;
import org.eclipse.jface.text.DocumentEvent;
import org.eclipse.jface.text.IDelayedInputChangeProvider;
import org.eclipse.jface.text.IDocument;
import org.eclipse.jface.text.IDocumentListener;
import org.eclipse.jface.text.IInformationControl;
import org.eclipse.jface.text.IInformationControlCreator;
import org.eclipse.jface.text.IInformationControlExtension2;
import org.eclipse.jface.text.IInformationControlExtension4;
import org.eclipse.jface.text.IInputChangedListener;
import org.eclipse.jface.text.IRegion;
import org.eclipse.jface.text.ITextHover;
import org.eclipse.jface.text.ITextHoverExtension;
import org.eclipse.jface.text.ITextHoverExtension2;
import org.eclipse.jface.text.ITextPresentationListener;
import org.eclipse.jface.text.ITextViewer;
import org.eclipse.jface.text.Position;
import org.eclipse.jface.text.Region;
import org.eclipse.jface.text.TextAttribute;
import org.eclipse.jface.text.TextPresentation;
import org.eclipse.jface.text.TextSelection;
import org.eclipse.jface.text.TextViewer;
import org.eclipse.jface.text.contentassist.CompletionProposal;
import org.eclipse.jface.text.contentassist.ContentAssistant;
import org.eclipse.jface.text.contentassist.ContextInformation;
import org.eclipse.jface.text.contentassist.ICompletionProposal;
import org.eclipse.jface.text.contentassist.IContentAssistProcessor;
import org.eclipse.jface.text.contentassist.IContentAssistant;
import org.eclipse.jface.text.contentassist.IContextInformation;
import org.eclipse.jface.text.contentassist.IContextInformationValidator;
import org.eclipse.jface.text.hyperlink.IHyperlink;
import org.eclipse.jface.text.hyperlink.IHyperlinkDetector;
import org.eclipse.jface.text.presentation.IPresentationReconciler;
import org.eclipse.jface.text.presentation.PresentationReconciler;
import org.eclipse.jface.text.rules.DefaultDamagerRepairer;
import org.eclipse.jface.text.rules.IToken;
import org.eclipse.jface.text.rules.ITokenScanner;
import org.eclipse.jface.text.source.Annotation;
import org.eclipse.jface.text.source.DefaultAnnotationHover;
import org.eclipse.jface.text.source.IAnnotationHover;
import org.eclipse.jface.text.source.ISourceViewer;
import org.eclipse.jface.text.source.IVerticalRuler;
import org.eclipse.jface.text.source.SourceViewerConfiguration;
import org.eclipse.jface.text.source.projection.ProjectionAnnotation;
import org.eclipse.jface.text.source.projection.ProjectionAnnotationModel;
import org.eclipse.jface.text.source.projection.ProjectionSupport;
import org.eclipse.jface.text.source.projection.ProjectionViewer;
import org.eclipse.jface.util.SafeRunnable;
import org.eclipse.jface.viewers.CellEditor;
import org.eclipse.jface.viewers.ISelection;
import org.eclipse.jface.viewers.ISelectionChangedListener;
import org.eclipse.jface.viewers.ISelectionProvider;
import org.eclipse.jface.viewers.IStructuredSelection;
import org.eclipse.jface.viewers.ITreeContentProvider;
import org.eclipse.jface.viewers.LabelProvider;
import org.eclipse.jface.viewers.SelectionChangedEvent;
import org.eclipse.jface.viewers.StructuredSelection;
import org.eclipse.jface.viewers.StructuredViewer;
import org.eclipse.jface.viewers.TreeViewer;
import org.eclipse.jface.viewers.Viewer;
import org.eclipse.swt.SWT;
import org.eclipse.swt.SWTError;
import org.eclipse.swt.browser.Browser;
import org.eclipse.swt.browser.LocationListener;
import org.eclipse.swt.browser.OpenWindowListener;
import org.eclipse.swt.browser.ProgressAdapter;
import org.eclipse.swt.browser.ProgressEvent;
import org.eclipse.swt.browser.WindowEvent;
import org.eclipse.swt.custom.StyleRange;
import org.eclipse.swt.custom.StyledText;
import org.eclipse.swt.custom.VerifyKeyListener;
import org.eclipse.swt.events.KeyEvent;
import org.eclipse.swt.events.KeyListener;
import org.eclipse.swt.events.ModifyEvent;
import org.eclipse.swt.events.ModifyListener;
import org.eclipse.swt.events.MouseEvent;
import org.eclipse.swt.events.MouseListener;
import org.eclipse.swt.events.SelectionEvent;
import org.eclipse.swt.events.SelectionListener;
import org.eclipse.swt.events.VerifyEvent;
import org.eclipse.swt.events.VerifyListener;
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.graphics.Font;
import org.eclipse.swt.graphics.FontData;
import org.eclipse.swt.graphics.FontMetrics;
import org.eclipse.swt.graphics.GC;
import org.eclipse.swt.graphics.Point;
import org.eclipse.swt.graphics.RGB;
import org.eclipse.swt.graphics.Rectangle;
import org.eclipse.swt.graphics.TextLayout;
import org.eclipse.swt.graphics.TextStyle;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.program.Program;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Combo;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.Dialog;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Label;
import org.eclipse.swt.widgets.Link;
import org.eclipse.swt.widgets.Listener;
import org.eclipse.swt.widgets.Menu;
import org.eclipse.swt.widgets.ScrollBar;
import org.eclipse.swt.widgets.Scrollable;
import org.eclipse.swt.widgets.Shell;
import org.eclipse.swt.widgets.Slider;
import org.eclipse.ui.IEditorDescriptor;
import org.eclipse.ui.IEditorInput;
import org.eclipse.ui.IEditorPart;
import org.eclipse.ui.IMemento;
import org.eclipse.ui.IPartListener2;
import org.eclipse.ui.ISharedImages;
import org.eclipse.ui.IWorkbench;
import org.eclipse.ui.IWorkbenchPage;
import org.eclipse.ui.IWorkbenchPart;
import org.eclipse.ui.IWorkbenchPartReference;
import org.eclipse.ui.IWorkbenchPreferencePage;
import org.eclipse.ui.PartInitException;
import org.eclipse.ui.PlatformUI;
import org.eclipse.ui.XMLMemento;
import org.eclipse.ui.editors.text.EditorsUI;
import org.eclipse.ui.editors.text.FileDocumentProvider;
import org.eclipse.ui.editors.text.TextEditor;
import org.eclipse.ui.part.FileEditorInput;
import org.eclipse.ui.part.IPageSite;
import org.eclipse.ui.part.Page;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.ui.texteditor.ContentAssistAction;
import org.eclipse.ui.texteditor.ITextEditorActionDefinitionIds;
import org.eclipse.ui.views.contentoutline.IContentOutlinePage;
import org.eclipse.ui.views.properties.IPropertyDescriptor;
import org.eclipse.ui.views.properties.IPropertySheetPage;
import org.eclipse.ui.views.properties.IPropertySource;
import org.eclipse.ui.views.properties.PropertySheetPage;
import org.emftext.runtime.EMFTextRuntimePlugin;
import org.emftext.runtime.IInputStreamProcessorProvider;
import org.emftext.runtime.IOptionProvider;
import org.emftext.runtime.IOptions;
import org.emftext.runtime.IResourcePostProcessor;
import org.emftext.runtime.InputStreamProcessor;
import org.emftext.runtime.resource.EProblemType;
import org.emftext.runtime.resource.IBracketPair;
import org.emftext.runtime.resource.ICommand;
import org.emftext.runtime.resource.IContextDependentURIFragment;
import org.emftext.runtime.resource.IElementMapping;
import org.emftext.runtime.resource.IExpectedElement;
import org.emftext.runtime.resource.IHoverTextProvider;
import org.emftext.runtime.resource.ILocationMap;
import org.emftext.runtime.resource.IParseResult;
import org.emftext.runtime.resource.IProblem;
import org.emftext.runtime.resource.IReferenceMapping;
import org.emftext.runtime.resource.IReferenceResolveResult;
import org.emftext.runtime.resource.IReferenceResolver;
import org.emftext.runtime.resource.IReferenceResolverSwitch;
import org.emftext.runtime.resource.ITextDiagnostic;
import org.emftext.runtime.resource.ITextParser;
import org.emftext.runtime.resource.ITextPrinter;
import org.emftext.runtime.resource.ITextResource;
import org.emftext.runtime.resource.ITextResourcePluginMetaInformation;
import org.emftext.runtime.resource.ITextScanner;
import org.emftext.runtime.resource.ITextToken;
import org.emftext.runtime.resource.ITokenResolveResult;
import org.emftext.runtime.resource.ITokenResolver;
import org.emftext.runtime.resource.ITokenResolverFactory;
import org.emftext.runtime.resource.ITokenStyle;
import org.emftext.runtime.resource.IURIMapping;
import org.emftext.runtime.resource.impl.AbstractBracketPair;
import org.emftext.runtime.resource.impl.AbstractEMFTextParser;
import org.emftext.runtime.resource.impl.AbstractEMFTextScanner;
import org.emftext.runtime.resource.impl.AbstractParseResult;
import org.emftext.runtime.resource.impl.AbstractProblem;
import org.emftext.runtime.resource.impl.AbstractReferenceMapping;
import org.emftext.runtime.resource.impl.AbstractTextResource;
import org.emftext.runtime.resource.impl.AbstractTextResourcePluginMetaInformation;
import org.emftext.runtime.resource.impl.AbstractTokenResolver;
import org.emftext.runtime.resource.impl.AbstractTokenStyle;
import org.emftext.runtime.resource.impl.TerminateParsingException;
import org.emftext.runtime.resource.impl.code_completion.CodeCompletionHelper;
import org.emftext.runtime.ui.AntlrTokenHelper;
import org.emftext.runtime.ui.IBackgroundParsingListener;
import org.emftext.runtime.ui.IBackgroundParsingStrategy;
import org.emftext.runtime.ui.MarkerHelper;
import org.emftext.runtime.ui.impl.AbstractBackgroundParsingListener;
import org.emftext.runtime.ui.impl.AbstractBackgroundParsingStrategy;
import org.emftext.runtime.ui.preferences.PreferenceConstants;
import org.emftext.runtime.ui.preferences.PreferenceInitializer;
import org.emftext.runtime.ui.preferences.SyntaxColoringHelper;
import org.emftext.runtime.ui.preferences.SyntaxColoringHelper.StyleProperty;
import org.emftext.runtime.util.CastUtil;
import org.emftext.runtime.util.CopiedEList;
import org.emftext.runtime.util.CopiedEObjectInternalEList;
import org.emftext.runtime.util.EObjectUtil;
import org.emftext.runtime.util.ListUtil;
import org.emftext.runtime.util.MapUtil;
import org.emftext.runtime.util.StringUtil;
import org.osgi.framework.Bundle;
import org.osgi.framework.BundleContext;

/**
 * Constants for class names used in the generated code.
 * 
 * TODO find all other occurrences of class names in the generator package
 * and use constants instead. 
 */
public interface IClassNameConstants {
	public String I_INFORMATION_CONTROL_EXTENSION4 = IInformationControlExtension4.class.getName();
	public String ABSTRACT_BACKGROUND_PARSING_STRATEGY = AbstractBackgroundParsingStrategy.class.getName();
	public String ABSTRACT_BACKGROUND_PARSING_LISTENER = AbstractBackgroundParsingListener.class.getName();
	public String ABSTRACT_BRACKET_PAIR = AbstractBracketPair.class.getName();
	public String ABSTRACT_EMF_TEXT_PARSER = AbstractEMFTextParser.class.getName();
	public String ABSTRACT_EMF_TEXT_SCANNER = AbstractEMFTextScanner.class.getName();
	public String ABSTRACT_INFORMATION_CONTROL = AbstractInformationControl.class.getName();
	public String ABSTRACT_PARSE_RESULT = AbstractParseResult.class.getName();
	public String ABSTRACT_PREFERENCE_INITIALIZER = AbstractPreferenceInitializer.class.getName();
	public String ABSTRACT_PROBLEM = AbstractProblem.class.getName();
	public String ABSTRACT_REFERENCE_MAPPING = AbstractReferenceMapping.class.getName();
	public String ABSTRACT_REUSABLE_INFORMATION_CONTROL_CREATOR = AbstractReusableInformationControlCreator.class.getName();
	public String ABSTRACT_TEXT_RESOURCE = AbstractTextResource.class.getName();
	public String ABSTRACT_TEXT_RESOURCE_PLUGIN_META_INFORMATION = AbstractTextResourcePluginMetaInformation.class.getName();
	public String ABSTRACT_TOKEN_RESOLVER = AbstractTokenResolver.class.getName();
	public String ABSTRACT_TOKEN_STYLE = AbstractTokenStyle.class.getName();
	public String ABSTRACT_UI_PLUGIN = AbstractUIPlugin.class.getName();
	public String ACTION = Action.class.getName();
	public String ADAPTER_FACTORY_CONTENT_PROVIDER = AdapterFactoryContentProvider.class.getName();
	public String ADAPTER_FACTORY_EDITING_DOMAIN = AdapterFactoryEditingDomain.class.getName();
	public String ADAPTER_FACTORY_LABEL_PROVIDER = AdapterFactoryLabelProvider.class.getName();
	public String ADAPTER_IMPL = AdapterImpl.class.getName();
	public String ANNOTATION = Annotation.class.getName();
	public String ANTLR_STRING_STREAM = ANTLRStringStream.class.getName();
	public String ANTLR_TOKEN_HELPER = AntlrTokenHelper.class.getName();
	public String ARRAYS = java.util.Arrays.class.getName();
	public String ARRAY_LIST = ArrayList.class.getName();
	public String ASSERT = Assert.class.getName();
	public String BAD_LOCATION_EXCEPTION = BadLocationException.class.getName();
	public String BAD_POSITION_CATEGORY_EXCEPTION = BadPositionCategoryException.class.getName();
	public String BASIC_COMMAND_STACK = BasicCommandStack.class.getName();
	public String BASIC_E_LIST = BasicEList.class.getName();
	public String BASIC_E_MAP = BasicEMap.class.getName();
	public String BIT_SET = BitSet.class.getName();
	public String BROWSER = Browser.class.getName();
	public String BUFFERED_OUTPUT_STREAM = BufferedOutputStream.class.getName();
	public String BUFFERED_READER = BufferedReader.class.getName();
	public String BUNDLE = Bundle.class.getName();
	public String BUNDLE_CONTEXT = BundleContext.class.getName();
	public String BUTTON = Button.class.getName();
	public String BYTE_ARRAY_INPUT_STREAM = ByteArrayInputStream.class.getName();
	public String CAST_UTIL = CastUtil.class.getName();
	public String CELL_EDITOR = CellEditor.class.getName();
	public String CODE_COMPLETION_HELPER = CodeCompletionHelper.class.getName();
	public String COLLECTION = Collection.class.getName();
	public String COLLECTIONS = Collections.class.getName();
	public String COLOR = Color.class.getName();
	public String COLOR_SELECTOR = ColorSelector.class.getName();
	public String COMBO = Combo.class.getName();
	public String COMMON_TOKEN = CommonToken.class.getName();
	public String COMPARATOR = Comparator.class.getName();
	public String COMPLETION_PROPOSAL = CompletionProposal.class.getName();
	public String COMPOSED_ADAPTER_FACTORY = ComposedAdapterFactory.class.getName();
	public String COMPOSITE = Composite.class.getName();
	public String CONTENT_ASSISTANT = ContentAssistant.class.getName();
	public String CONTENT_ASSIST_ACTION = ContentAssistAction.class.getName();
	public String CONTEXT_INFORMATION = ContextInformation.class.getName();
	public String CONTROL = Control.class.getName();
	public String COPIED_E_LIST = CopiedEList.class.getName();
	public String COPIED_E_OBJECT_INTERNAL_E_LIST = CopiedEObjectInternalEList.class.getName();
	public String CORE_EXCEPTION = CoreException.class.getName();
	public String DEFAULT_ANNOTATION_HOVER = DefaultAnnotationHover.class.getName();
	public String DEFAULT_DAMAGER_REPAIRER = DefaultDamagerRepairer.class.getName();
	public String DEFAULT_INFORMATION_CONTROL = DefaultInformationControl.class.getName();
	public String DIAGNOSTIC = Diagnostic.class.getCanonicalName();
	public String DIALOG = Dialog.class.getName();
	public String DISPLAY = Display.class.getName();
	public String DOCUMENT = Document.class.getName();
	public String DOCUMENT_EVENT = DocumentEvent.class.getName();
	public String DOCUMENT_LISTENER = DocumentListener.class.getName();
	public String EARLY_EXIT_EXCEPTION = EarlyExitException.class.getName();
	public String ECORE_ITEM_PROVIDER_ADAPTER_FACTORY = EcoreItemProviderAdapterFactory.class.getName();
	public String ECORE_UTIL = EcoreUtil.class.getName();
	public String EDITING_DOMAIN = EditingDomain.class.getName();
	public String EDITOR = Editor.class.getName();
	public String EDITORS_UI = EditorsUI.class.getName();
	public String ELEMENT_BASED_TEXT_DIAGNOSTIC = "ElementBasedTextDiagnostic";
	public String EMFTEXT_RUNTIME_PLUGIN = EMFTextRuntimePlugin.class.getName();
	public String EXCEPTION = Exception.class.getName();
	public String E_ATTRIBUTE = EAttribute.class.getName();
	public String E_CLASS = EClass.class.getName();
	public String E_ENUM = EEnum.class.getName();
	public String E_ENUM_LITERAL = EEnumLiteral.class.getName();
	public String E_LIST = EList.class.getName();
	public String E_MAP = EMap.class.getName();
	public String E_OBJECT = EObject.class.getName();
	public String E_OBJECT_IMPL = EObjectImpl.class.getName();
	public String E_OBJECT_UTIL = EObjectUtil.class.getName();
	public String E_OPERATION = EOperation.class.getName();
	public String E_PROBLEM_TYPE = EProblemType.class.getName();
	public String E_REFERENCE = EReference.class.getName();
	public String E_STRUCTURAL_FEATURE = EStructuralFeature.class.getName();
	public String FAILED_PREDICATE_EXCEPTION = FailedPredicateException.class.getName();
	public String FILE = File.class.getName();
	public String FILE_DOCUMENT_PROVIDER = FileDocumentProvider.class.getName();
	public String FILE_EDITOR_INPUT = FileEditorInput.class.getName();
	public String FILE_INPUT_STREAM = FileInputStream.class.getName();
	public String FILE_OUTPUT_STREAM = FileOutputStream.class.getName();
	public String FONT = Font.class.getName();
	public String FONT_DATA = FontData.class.getName();
	public String FONT_METRICS = FontMetrics.class.getName();
	public String GC = GC.class.getName();
	public String GRID_DATA = GridData.class.getName();
	public String GRID_LAYOUT = GridLayout.class.getName();
	public String HASH_MAP = HashMap.class.getName();
	public String HASH_SET = HashSet.class.getName();
	public String ILLEGAL_ARGUMENT_EXCEPTION = IllegalArgumentException.class.getName();
	public String INPUT_STREAM = InputStream.class.getName();
	public String INPUT_STREAM_PROCESSOR = InputStreamProcessor.class.getName();
	public String INPUT_STREAM_READER = InputStreamReader.class.getName();
	public String INTEGER = Integer.class.getName();
	public String INTERNAL_E_LIST = InternalEList.class.getName();
	public String INTERNAL_E_OBJECT = InternalEObject.class.getName();
	public String INT_STREAM = IntStream.class.getName();
	public String IO_EXCEPTION = IOException.class.getName();
	public String ITERATOR = Iterator.class.getName();
	public String I_ACTION = IAction.class.getName();
	public String I_ANNOTATION_HOVER = IAnnotationHover.class.getName();
	public String I_BACKGROUND_PARSING_LISTENER = IBackgroundParsingListener.class.getName();
	public String I_BACKGROUND_PARSING_STRATEGY = IBackgroundParsingStrategy.class.getName();
	public String I_BRACKET_PAIR = IBracketPair.class.getName();
	public String I_COMMAND = ICommand.class.getName();
	public String I_COMPLETION_PROPOSAL = ICompletionProposal.class.getName();
	public String I_CONFIGURATION_ELEMENT = IConfigurationElement.class.getName();
	public String I_CONTENT_ASSISTANT = IContentAssistant.class.getName();
	public String I_CONTENT_ASSIST_PROCESSOR = IContentAssistProcessor.class.getName();
	public String I_CONTENT_OUTLINE_PAGE = IContentOutlinePage.class.getName();
	public String I_CONTEXT_DEPENDENT_URI_FRAGMENT = IContextDependentURIFragment.class.getName();
	public String I_CONTEXT_DEPENDENT_URI_FRAGMENT_FACTORY = org.emftext.runtime.resource.IContextDependentURIFragmentFactory.class.getName();
	public String I_CONTEXT_INFORMATION = IContextInformation.class.getName();
	public String I_CONTEXT_INFORMATION_VALIDATOR = IContextInformationValidator.class.getName();
	public String I_DELAYED_INPUT_CHANGE_PROVIDER = IDelayedInputChangeProvider.class.getName();
	public String I_DIALOG_CONSTANTS = IDialogConstants.class.getName();
	public String I_DOCUMENT = IDocument.class.getName();
	public String I_DOCUMENT_LISTENER = IDocumentListener.class.getName();
	public String I_EDITING_DOMAIN_PROVIDER = IEditingDomainProvider.class.getName();
	public String I_EDITOR_DESCRIPTOR = IEditorDescriptor.class.getName();
	public String I_EDITOR_INPUT = IEditorInput.class.getName();
	public String I_EDITOR_PART = IEditorPart.class.getName();
	public String I_ELEMENT_MAPPING = IElementMapping.class.getName();
	public String I_EXPECTED_ELEMENT = IExpectedElement.class.getName();
	public String I_EXTENSION_REGISTRY = IExtensionRegistry.class.getName();
	public String I_FILE = IFile.class.getName();
	public String I_HOVER_TEXT_PROVIDER = IHoverTextProvider.class.getName();
	public String I_HYPERLINK = IHyperlink.class.getName();
	public String I_HYPERLINK_DETECTOR = IHyperlinkDetector.class.getName();
	public String I_INFORMATION_CONTROL = IInformationControl.class.getName();
	public String I_INFORMATION_CONTROL_CREATOR = IInformationControlCreator.class.getName();
	public String I_INFORMATION_CONTROL_EXTENSION2 = IInformationControlExtension2.class.getName();
	public String I_INPUT_CHANGED_LISTENER = IInputChangedListener.class.getName();
	public String I_INPUT_STREAM_PROCESSOR_PROVIDER = IInputStreamProcessorProvider.class.getName();
	public String I_ITEM_PROPERTY_DESCRIPTOR = IItemPropertyDescriptor.class.getName();
	public String I_ITEM_PROPERTY_SOURCE = IItemPropertySource.class.getName();
	public String I_LOCATION_MAP = ILocationMap.class.getName();
	public String I_MARKER = IMarker.class.getName();
	public String I_MEMENTO = IMemento.class.getName();
	public String I_OPTIONS = IOptions.class.getName();
	public String I_OPTION_PROVIDER = IOptionProvider.class.getName();
	public String I_PAGE_SITE = IPageSite.class.getName();
	public String I_PARSE_RESULT = IParseResult.class.getName();
	public String I_PART_LISTENER2 = IPartListener2.class.getName();
	public String I_PATH = IPath.class.getName();
	public String I_PREFERENCE_STORE = IPreferenceStore.class.getName();
	public String I_PRESENTATION_RECONCILER = IPresentationReconciler.class.getName();
	public String I_PROBLEM = IProblem.class.getName();
	public String I_PROGRESS_MONITOR = IProgressMonitor.class.getName();
	public String I_PROPERTY_DESCRIPTOR = IPropertyDescriptor.class.getName();
	public String I_PROPERTY_SHEET_PAGE = IPropertySheetPage.class.getName();
	public String I_PROPERTY_SOURCE = IPropertySource.class.getName();
	public String I_REFERENCE_MAPPING = IReferenceMapping.class.getName();
	public String I_REFERENCE_RESOLVER = IReferenceResolver.class.getName();
	public String I_REFERENCE_RESOLVER_SWITCH = IReferenceResolverSwitch.class.getName();
	public String I_REFERENCE_RESOLVE_RESULT = IReferenceResolveResult.class.getName();
	public String I_REGION = IRegion.class.getName();
	public String I_RESOURCE = IResource.class.getName();
	public String I_RESOURCE_CHANGE_EVENT = IResourceChangeEvent.class.getName();
	public String I_RESOURCE_CHANGE_LISTENER = IResourceChangeListener.class.getName();
	public String I_RESOURCE_DELTA = IResourceDelta.class.getName();
	public String I_RESOURCE_DELTA_VISITOR = IResourceDeltaVisitor.class.getName();
	public String I_RESOURCE_POST_PROCESSOR = IResourcePostProcessor.class.getName();
	public String I_RESOURCE_POST_PROCESSOR_PROVIDER = org.emftext.runtime.IResourcePostProcessorProvider.class.getName();
	public String I_SELECTION = ISelection.class.getName();
	public String I_SELECTION_CHANGED_LISTENER = ISelectionChangedListener.class.getName();
	public String I_SELECTION_PROVIDER = ISelectionProvider.class.getName();
	public String I_SHARED_IMAGES = ISharedImages.class.getName();
	public String I_SOURCE_VIEWER = ISourceViewer.class.getName();
	public String I_STRUCTURED_SELECTION = IStructuredSelection.class.getName();
	public String I_TEXT_DIAGNOSTIC = ITextDiagnostic.class.getName();
	public String I_TEXT_EDITOR_ACTION_DEFINITION_IDS = ITextEditorActionDefinitionIds.class.getName();
	public String I_TEXT_HOVER = ITextHover.class.getName();
	public String I_TEXT_HOVER_EXTENSION = ITextHoverExtension.class.getName();
	public String I_TEXT_HOVER_EXTENSION2 = ITextHoverExtension2.class.getName();
	public String I_TEXT_PARSER = ITextParser.class.getName();
	public String I_TEXT_PRESENTATION_LISTENER = ITextPresentationListener.class.getName();
	public String I_TEXT_PRINTER = ITextPrinter.class.getName();
	public String I_TEXT_RESOURCE = ITextResource.class.getName();
	public String I_TEXT_RESOURCE_PLUGIN_META_INFORMATION = ITextResourcePluginMetaInformation.class.getName();
	public String I_TEXT_SCANNER = ITextScanner.class.getName();
	public String I_TEXT_TOKEN = ITextToken.class.getName();
	public String I_TEXT_VIEWER = ITextViewer.class.getName();
	public String I_TOKEN = IToken.class.getName();
	public String I_TOKEN_RESOLVER = ITokenResolver.class.getName();
	public String I_TOKEN_RESOLVER_FACTORY = ITokenResolverFactory.class.getName();
	public String I_TOKEN_RESOLVE_RESULT = ITokenResolveResult.class.getName();
	public String I_TOKEN_SCANNER = ITokenScanner.class.getName();
	public String I_TOKEN_STYLE = ITokenStyle.class.getName();
	public String I_TREE_CONTENT_PROVIDER = ITreeContentProvider.class.getName();
	public String I_URI_MAPPING = IURIMapping.class.getName();
	public String I_VERTICAL_RULER = IVerticalRuler.class.getName();
	public String I_WORKBENCH = IWorkbench.class.getName();
	public String I_WORKBENCH_PAGE = IWorkbenchPage.class.getName();
	public String I_WORKBENCH_PART = IWorkbenchPart.class.getName();
	public String I_WORKBENCH_PART_REFERENCE = IWorkbenchPartReference.class.getName();
	public String I_WORKBENCH_PREFERENCE_PAGE = IWorkbenchPreferencePage.class.getName();
	public String I_WORKSPACE = IWorkspace.class.getName();
	public String I_WORKSPACE_ROOT = IWorkspaceRoot.class.getName();
	public String J_FACE_RESOURCES = JFaceResources.class.getName();
	public String KEY_EVENT = KeyEvent.class.getName();
	public String KEY_LISTENER = KeyListener.class.getName();
	public String LABEL = Label.class.getName();
	public String LABEL_PROVIDER = LabelProvider.class.getName();
	public String LEXER = Lexer.class.getName();
	public String LINK = Link.class.getName();
	public String LINKED_HASH_MAP = LinkedHashMap.class.getName();
	public String LINKED_HASH_SET = LinkedHashSet.class.getName();
	public String LINKED_LIST = LinkedList.class.getName();
	public String LIST = List.class.getName();
	public String LISTENER = Listener.class.getName();
	public String LISTENER_LIST = ListenerList.class.getName();
	public String LIST_ITERATOR = ListIterator.class.getName();
	public String LIST_UTIL = ListUtil.class.getName();
	public String LOCATION_LISTENER = LocationListener.class.getName();
	public String MANY_INVERSE = EObjectWithInverseResolvingEList.ManyInverse.class.getCanonicalName();
	public String MAP = Map.class.getName();
	public String MAP_UTIL = MapUtil.class.getName();
	//public String MARKER = Marker.class.getName();
	public String MARKER_HELPER = MarkerHelper.class.getName();
	public String MATCHER = Matcher.class.getName();
	public String MATH = Math.class.getName();
	//public String MEMENTO = Memento.class.getName();
	public String MENU = Menu.class.getName();
	public String MESSAGE_DIALOG = MessageDialog.class.getName();
	public String MESSAGE_DIGEST = MessageDigest.class.getName();
	public String MISMATCHED_NOT_SET_EXCEPTION = MismatchedNotSetException.class.getName();
	public String MISMATCHED_RANGE_EXCEPTION = MismatchedRangeException.class.getName();
	public String MISMATCHED_SET_EXCEPTION = MismatchedSetException.class.getName();
	public String MISMATCHED_TOKEN_EXCEPTION = MismatchedTokenException.class.getName();
	public String MISMATCHED_TREE_NODE_EXCEPTION = MismatchedTreeNodeException.class.getName();
	public String MODIFY_EVENT = ModifyEvent.class.getName();
	public String MODIFY_LISTENER = ModifyListener.class.getName();
	public String MOUSE_EVENT = MouseEvent.class.getName();
	public String MOUSE_LISTENER = MouseListener.class.getName();
	public String NOTIFICATION = Notification.class.getName();
	public String NO_SUCH_ALGORITHM_EXCEPTION = NoSuchAlgorithmException.class.getName();
	public String NO_VIABLE_ALT_EXCEPTION = NoViableAltException.class.getName();
	public String NULL_POINTER_EXCEPTION = NullPointerException.class.getName();
	public String OBJECT = Object.class.getName();
	public String OPEN_WINDOW_LISTENER = OpenWindowListener.class.getName();
	public String OUTPUT_STREAM = OutputStream.class.getName();
	public String OUTPUT_STREAM_WRITER = OutputStreamWriter.class.getName();
	public String PAGE = Page.class.getName();
	public String PART_INIT_EXCEPTION = PartInitException.class.getName();
	public String PATH = Path.class.getName();
	public String PATTERN = java.util.regex.Pattern.class.getName();
	public String PLATFORM = Platform.class.getName();
	public String PLATFORM_UI = PlatformUI.class.getName();
	public String POINT = Point.class.getName();
	public String POSITION = Position.class.getName();
	public String POSITION_BASED_TEXT_DIAGNOSTIC = "PositionBasedTextDiagnostic";
	public String PREFERENCE_CONSTANTS = PreferenceConstants.class.getName();
	public String PREFERENCE_CONVERTER = PreferenceConverter.class.getName();
	public String PREFERENCE_INITIALIZER = PreferenceInitializer.class.getName();
	public String PREFERENCE_PAGE = PreferencePage.class.getName();
	public String PRESENTATION_RECONCILER = PresentationReconciler.class.getName();
	public String PRINTER_WRITER = PrintWriter.class.getName();
	public String PROGRAM = Program.class.getName();
	public String PROGRESS_ADAPTER = ProgressAdapter.class.getName();
	public String PROGRESS_EVENT = ProgressEvent.class.getName();
	public String PROJECTION_ANNOTATION = ProjectionAnnotation.class.getName();
	public String PROJECTION_ANNOTATION_MODEL = ProjectionAnnotationModel.class.getName();
	public String PROJECTION_SUPPORT = ProjectionSupport.class.getName();
	public String PROJECTION_VIEWER = ProjectionViewer.class.getName();
	public String PROPERTY_DESCRIPTOR = PropertyDescriptor.class.getName();
	public String PROPERTY_SHEET_PAGE = PropertySheetPage.class.getName();
	public String PROPERTY_SOURCE = PropertySource.class.getName();
	public String PUSHBACK_READER = PushbackReader.class.getName();
	public String READER = Reader.class.getName();
	public String RECOGNITION_EXCEPTION = RecognitionException.class.getName();
	public String RECTANGLE = Rectangle.class.getName();
	public String REFLECTIVE_ITEM_PROVIDER_ADAPTER_FACTORY = ReflectiveItemProviderAdapterFactory.class.getName();
	public String REGION = Region.class.getName();
	public String RESOLVER_SWITCH_FIELD_NAME = "resolverSwitch";
	public String RESOURCE = org.eclipse.emf.ecore.resource.Resource.class.getName();
	public String RESOURCES_PLUGIN = ResourcesPlugin.class.getName();
	public String RESOURCE_BUNDLE = ResourceBundle.class.getName();
	public String RESOURCE_ITEM_PROVIDER_ADAPTER_FACTORY = ResourceItemProviderAdapterFactory.class.getName();
	public String RESOURCE_SET = ResourceSet.class.getName();
	public String RGB = RGB.class.getName();
	public String RUNNABLE = Runnable.class.getName();
	public String RUNTIME_EXCEPTION = RuntimeException.class.getName();
	public String SAFE_RUNNABLE = SafeRunnable.class.getName();
	public String SAFE_RUNNER = SafeRunner.class.getName();
	public String SCROLLABLE = Scrollable.class.getName();
	public String SCROLL_BAR = ScrollBar.class.getName();
	public String SELECTION_CHANGED_EVENT = SelectionChangedEvent.class.getName();
	public String SELECTION_EVENT = SelectionEvent.class.getName();
	public String SELECTION_LISTENER = SelectionListener.class.getName();
	public String SET = Set.class.getName();
	public String SHELL = Shell.class.getName();
	public String SLIDER = Slider.class.getName();
	public String SOURCE_VIEWER_CONFIGURATION = SourceViewerConfiguration.class.getName();
	public String STACK = Stack.class.getName();
	public String STRING = String.class.getName();
	public String STRING_READER = StringReader.class.getName();
	public String STRING_UTIL = StringUtil.class.getName();
	public String STRING_WRITER = StringWriter.class.getName();
	public String STRUCTURED_SELECTION = StructuredSelection.class.getName();
	public String STRUCTURED_VIEWER = StructuredViewer.class.getName();
	public String STYLED_TEXT = StyledText.class.getName();
	public String STYLE_PROPERTY = StyleProperty.class.getCanonicalName();
	public String STYLE_RANGE = StyleRange.class.getName();
	public String SWT = SWT.class.getName();
	public String SWT_ERROR = SWTError.class.getName();
	public String SYNTAX_COLORING_HELPER = SyntaxColoringHelper.class.getName();
	public String TERMINATE_PARSING_EXCEPTION = TerminateParsingException.class.getName();
	public String TEXT_ATTRIBUTE = TextAttribute.class.getName();
	public String TEXT_EDITOR = TextEditor.class.getName();
	public String TEXT_LAYOUT = TextLayout.class.getName();
	public String TEXT_PRESENTATION = TextPresentation.class.getName();
	public String TEXT_SELECTION = TextSelection.class.getName();
	public String TEXT_STYLE = TextStyle.class.getName();
	public String TEXT_VIEWER = TextViewer.class.getName();
	public String TIMER = Timer.class.getName();
	public String TIMER_TASK = TimerTask.class.getName();
	public String TOKEN = Token.class.getName();
	public String TOOL_BAR_MANAGER = ToolBarManager.class.getName();
	public String TREE_VIEWER = TreeViewer.class.getName();
	public String URI = org.eclipse.emf.common.util.URI.class.getName();
	public String URI_CONVERTER = URIConverter.class.getName();
	public String URL = URL.class.getName();
	public String VERIFY_EVENT = VerifyEvent.class.getName();
	public String VERIFY_KEY_LISTENER = VerifyKeyListener.class.getName();
	public String VERIFY_LISTENER = VerifyListener.class.getName(); 
	public String VIEWER = Viewer.class.getName();
	public String WINDOW_EVENT = WindowEvent.class.getName();
	public String XML_MEMENTO = XMLMemento.class.getName();
	public String SWT_LIST = org.eclipse.swt.widgets.List.class.getName();
	public String JFACE_DIALOG = org.eclipse.jface.dialogs.Dialog.class.getName();
}
