<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="xmas"
    nsURI="http://www.emftext.org/xmas" nsPrefix="xmas">
  <eClassifiers xsi:type="ecore:EClass" name="PresentList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="presents" upperBound="-1"
        eType="#//Present" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Present">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributes" upperBound="-1"
        eType="#//AttributeEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="for" lowerBound="1" eType="#//Person"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AttributeEnum">
    <eLiterals name="NEW" literal="new"/>
    <eLiterals name="NICE" value="1" literal="nice"/>
    <eLiterals name="FANCY" value="2" literal="fancy"/>
    <eLiterals name="COMPLETE" value="3" literal="complete"/>
    <eLiterals name="CONVENIENT" value="4" literal="convenient"/>
    <eLiterals name="LIGHTWEIGHT" value="5" literal="lightweight"/>
    <eLiterals name="LARGE" value="6" literal="large"/>
    <eLiterals name="ADVANCED" value="7" literal="advanced"/>
    <eLiterals name="SEAMLESS" value="8" literal="seamless"/>
  </eClassifiers>
</ecore:EPackage>
