<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="content"
    nsURI="http://www.emftext.org/test/content" nsPrefix="content">
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//ChildA" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChildA">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nonContained" upperBound="-1"
        eType="#//ChildA"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="integer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="string" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" eType="#//MyEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MyEnum">
    <eLiterals name="valueA" literal="A"/>
  </eClassifiers>
</ecore:EPackage>
