<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="extendingsyntax5"
    nsURI="http://www.emftext.org/test/extendingsyntax5" nsPrefix="extendingsyntax5">
  <eClassifiers xsi:type="ecore:EClass" name="E5">
    <eStructuralFeatures xsi:type="ecore:EReference" name="b1" lowerBound="1" eType="ecore:EClass basesyntax1.ecore#//B1"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="b4" lowerBound="1" eType="ecore:EClass basesyntax4.ecore#//B4"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
