<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="prolog"
    nsURI="http://www.emftext.org/language/prolog" nsPrefix="prolog">
  <eClassifiers xsi:type="ecore:EClass" name="PrologProgram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clauses" lowerBound="1"
        upperBound="-1" eType="#//Clause" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" lowerBound="1"
        eType="#//Predicate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conjunction" eType="#//Conjunction"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Term" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Numeral" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Term #//Tail">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="List" eSuperTypes="#//Term #//Tail">
    <eStructuralFeatures xsi:type="ecore:EReference" name="headTerms" upperBound="-1"
        eType="#//Term" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tail" eType="#//Tail" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Predicate" eSuperTypes="#//Part #//Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="terms" upperBound="-1"
        eType="#//Term" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableReference" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnonymousVariable" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tail" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="#//Part">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//VariableReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" lowerBound="1" eType="#//Term"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conjunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" lowerBound="1" upperBound="-1"
        eType="#//Part" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Part" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Additive" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//ADDITIVE_OPERATOR"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Term"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//Term"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ADDITIVE_OPERATOR">
    <eLiterals name="plus" literal="PLUS"/>
    <eLiterals name="minus" value="1" literal="MINUS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplicative" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//MULTIPLICATIVE_OPERATOR"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Term"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//Term"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MULTIPLICATIVE_OPERATOR">
    <eLiterals name="mult" literal="MULT"/>
    <eLiterals name="div" value="1" literal="DIV"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Power" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" lowerBound="1" eType="#//Term"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exponent" lowerBound="1"
        eType="#//Term" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Negation" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//ADDITIVE_OPERATOR"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//Term"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BracketExpression" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//Term"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
