/*******************************************************************************
 * Copyright (c) 2006-2010 
 * Software Technology Group, Dresden University of Technology
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0 
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *   Software Technology Group - TU Dresden, Germany 
 *      - initial API and implementation
 ******************************************************************************/
package org.emftext.sdk.codegen;

import org.emftext.sdk.IPluginDescriptor;
import org.emftext.sdk.concretesyntax.ConcreteSyntax;
import org.emftext.sdk.concretesyntax.OptionTypes;

/**
 * An enumeration of all plug-in types that might be generated by EMFText.
 */
public abstract class PluginDescriptor implements IPluginDescriptor<GenerationContext> {

	private OptionTypes option;
	
	public PluginDescriptor(OptionTypes option) {
		this.option = option;
	}
	
	public OptionTypes getOption() {
		return option;
	}

	public String getName(GenerationContext context) {
		if (context == null) {
			return getName((ConcreteSyntax) null);
		} else {
			ConcreteSyntax syntax = context.getConcreteSyntax();
			return getName(syntax);
		}
	}

	public abstract String getName(ConcreteSyntax syntax);

	public abstract String getBasePackage(ConcreteSyntax syntax);
}
