<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bug1154"
    nsURI="http://www.emftext.org/test/bug1154" nsPrefix="bug1154">
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Child" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Child" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BackslashBegin" eSuperTypes="#//Child"/>
  <eClassifiers xsi:type="ecore:EClass" name="BackslashN" eSuperTypes="#//Child"/>
  <eClassifiers xsi:type="ecore:EClass" name="BackslashR" eSuperTypes="#//Child"/>
  <eClassifiers xsi:type="ecore:EClass" name="BackslashT" eSuperTypes="#//Child"/>
  <eClassifiers xsi:type="ecore:EClass" name="BackslashB" eSuperTypes="#//Child"/>
  <eClassifiers xsi:type="ecore:EClass" name="BackslashF" eSuperTypes="#//Child"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleQuote" eSuperTypes="#//Child"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingleQuote" eSuperTypes="#//Child"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingleBackslash" eSuperTypes="#//Child"/>
  <eClassifiers xsi:type="ecore:EClass" name="BackslashInWord" eSuperTypes="#//Child"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnicodeFFFF" eSuperTypes="#//Child"/>
  <eClassifiers xsi:type="ecore:EClass" name="Percent" eSuperTypes="#//Child"/>
</ecore:EPackage>
