package TypeArguments ta "http://www.emftext.org/test/ecore/TypeArguments" {

	class <TypeParam1> GenericClassA {
		attribute EString attribute1;
	}

	class <TypeParameterB> ClassB {
		reference GenericClassA rawReferenceToA;
		reference typed GenericClassA<typed ClassB> typedReferenceToA;
		reference typed <TypeParameterB> GenericClassA<typed ClassB> typedReferenceToA;
	}
}