<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cct3"
    nsURI="http://www.emftext.org/test/cct3" nsPrefix="cct3">
  <eClassifiers xsi:type="ecore:EClass" name="M1"/>
  <eClassifiers xsi:type="ecore:EClass" name="M2"/>
  <eClassifiers xsi:type="ecore:EClass" name="M3"/>
  <eClassifiers xsi:type="ecore:EClass" name="M4"/>
  <eClassifiers xsi:type="ecore:EClass" name="M5">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//M5Sub" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="M5Sub"/>
  <eClassifiers xsi:type="ecore:EClass" name="M6">
    <eStructuralFeatures xsi:type="ecore:EReference" name="self" upperBound="-1" eType="#//M6"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="M7"/>
  <eClassifiers xsi:type="ecore:EClass" name="M8">
    <eStructuralFeatures xsi:type="ecore:EReference" name="m9" upperBound="-1" eType="#//M9"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="M9"/>
  <eClassifiers xsi:type="ecore:EClass" name="M10">
    <eStructuralFeatures xsi:type="ecore:EReference" name="m11" upperBound="-1" eType="#//M11"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="M11">
    <eStructuralFeatures xsi:type="ecore:EReference" name="m10" upperBound="-1" eType="#//M10"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="M12">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="M13">
    <eStructuralFeatures xsi:type="ecore:EReference" name="m14" upperBound="-1" eType="#//M14"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="M14"/>
  <eClassifiers xsi:type="ecore:EClass" name="M15">
    <eStructuralFeatures xsi:type="ecore:EReference" name="m16" lowerBound="1" eType="#//M16"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="M16">
    <eStructuralFeatures xsi:type="ecore:EReference" name="m17" lowerBound="1" eType="#//M17"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="M17">
    <eStructuralFeatures xsi:type="ecore:EReference" name="m18" lowerBound="1" eType="#//M18"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="M18">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
