<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="generics" nsURI="http://www.emftext.org/test/generics" nsPrefix="generics">
  <eClassifiers xsi:type="ecore:EClass" name="GenericsTestModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenericTypeWithAttribute" abstract="true"
      eSuperTypes="#//Type">
    <eTypeParameters name="T"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eGenericType eTypeParameter="#//GenericTypeWithAttribute/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteTypeWithAttribute1">
    <eGenericSuperTypes eClassifier="#//GenericTypeWithAttribute">
      <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteTypeWithAttribute2">
    <eGenericSuperTypes eClassifier="#//GenericTypeWithAttribute">
      <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericTypeWithNCReference" abstract="true"
      eSuperTypes="#//Type">
    <eTypeParameters name="T"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1">
      <eGenericType eTypeParameter="#//GenericTypeWithNCReference/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteTypeWithNCReference1">
    <eGenericSuperTypes eClassifier="#//GenericTypeWithNCReference">
      <eTypeArguments eClassifier="#//BasicType1"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteTypeWithNCReference2">
    <eGenericSuperTypes eClassifier="#//GenericTypeWithNCReference">
      <eTypeArguments eClassifier="#//BasicType2"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicType1" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="BasicType2" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenericTypeWithContainmentReference"
      abstract="true" eSuperTypes="#//Type">
    <eTypeParameters name="T"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" containment="true">
      <eGenericType eTypeParameter="#//GenericTypeWithContainmentReference/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteTypeWithContainmentReference1">
    <eGenericSuperTypes eClassifier="#//GenericTypeWithContainmentReference">
      <eTypeArguments eClassifier="#//BasicType1"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteTypeWithContainmentReference2">
    <eGenericSuperTypes eClassifier="#//GenericTypeWithContainmentReference">
      <eTypeArguments eClassifier="#//BasicType2"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
