<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="invalid_regex1"
    nsURI="http://www.emftext.org/test/invalid_regex1" nsPrefix="invalid_regex1">
  <eClassifiers xsi:type="ecore:EClass" name="Main"/>
</ecore:EPackage>
