<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="models"
    nsURI="http://www.emftext.org/language/models" nsPrefix="models">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hair" eType="#//Color"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lips" eType="#//Color"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eyes" eType="#//Color"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="legs" eType="#//Size"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Color">
    <eLiterals name="blond"/>
    <eLiterals name="blue" value="1"/>
    <eLiterals name="red" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Size">
    <eLiterals name="endless"/>
  </eClassifiers>
</ecore:EPackage>
