<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cct4"
    nsURI="http://www.emftext.org/test/cct4" nsPrefix="cct4">
  <eClassifiers xsi:type="ecore:EClass" name="Root1">
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" lowerBound="1" eType="#//Child"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Child">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subChild" lowerBound="1"
        eType="#//SubChild" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubChild">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subSubChild" lowerBound="1"
        eType="#//SubSubChild" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubSubChild">
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" lowerBound="1" eType="#//Root1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root2">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Root2Child" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root2Child" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Target" eSuperTypes="#//Root2Child">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//Root2Child">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
        eType="#//Target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root3">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targets" lowerBound="1"
        upperBound="-1" eType="#//Target" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
        eType="#//Target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root4">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enumAttribute" lowerBound="1"
        eType="#//Root4Enum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Root4Enum">
    <eLiterals name="spring"/>
    <eLiterals name="summer" value="1"/>
    <eLiterals name="autumn" value="2"/>
    <eLiterals name="winter" value="3"/>
  </eClassifiers>
</ecore:EPackage>
