<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="puteverywhere"
    nsURI="http://www.emftext.org/test/puteverywhere" nsPrefix="org.emftext.test">
  <eClassifiers xsi:type="ecore:EClass" name="Annotable">
    <eAnnotations source="isPutEverywhere"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comments" upperBound="-1"
        eType="#//Comment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linebreaks" upperBound="-1"
        eType="#//NewLine" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root" eSuperTypes="#//Annotable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" upperBound="-1"
        eType="#//Part" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Part" abstract="true" eSuperTypes="#//Annotable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pair" eSuperTypes="#//Part"/>
  <eClassifiers xsi:type="ecore:EClass" name="Triple" eSuperTypes="#//Part"/>
  <eClassifiers xsi:type="ecore:EClass" name="Comment"/>
  <eClassifiers xsi:type="ecore:EClass" name="NewLine"/>
</ecore:EPackage>
