package org.emftext.sdk.concretesyntax.resource.cs;

import java.io.OutputStream;

import org.emftext.runtime.resource.ITextResource;

/**
* This is the printer class used by EMFText.
* Users may implement own behavior by overriding printing methods in the printer base.
* The baseclass contains a pretty printer implementation generated by EMFText which
* is not granted to work in all cases, but should work in most cases.
*/
public class CsPrinter extends CsPrinterBase {

	public CsPrinter(OutputStream o, ITextResource resource) {
		super(o, resource);
	}
}
